'use client';
import { Suspense, useEffect, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { usePathname, useSearchParams } from 'next/navigation';
import { ConnectedCompare, ConnectedOrganization, ConnectedRolePanel, ErrorState } from '../components/operational/ConnectedViews';
import { useAuth } from '../lib/api/auth-context';
import { HomeSearchExperience } from '../components/search/HomeSearchExperience';
import { UnifiedSearchView } from '../components/operational/UnifiedSearchView';

const hotels = [
  { name: 'هتل پارسیان آزادی', city: 'تهران', score: '۴.۷', price: '۷٬۸۵۰٬۰۰۰', image: '/images/figma/trip-north.jpeg', tag: 'بهترین کیفیت' },
  { name: 'هتل زندیه', city: 'شیراز', score: '۴.۵', price: '۵٬۹۹۰٬۰۰۰', image: '/images/figma/trip-shiraz.jpeg', tag: 'بهترین ارزش خرید' },
  { name: 'هتل قصر طلایی', city: 'مشهد', score: '۴.۶', price: '۶٬۷۵۰٬۰۰۰', image: '/images/figma/trip-qeshm.jpeg', tag: 'انتخاب سازمانی' }
];
const nav = [['خانه','/'], ['خدمات سفر','/#services'], ['پیشنهادها','/#offers'], ['تجربه مقصد','/#experiences'], ['سازمانی','/organization'], ['دستیار سفر','/assistant'], ['مقایسه','/compare'], ['اعتبار من','/employee'], ['White Label','/white-label'], ['BackOffice','/integrations']];

function Brand(){ return <Link className="brand" href="/" aria-label="کارن‌سیر، صفحه اصلی"><span className="brand-mark" aria-hidden="true">ک</span><span>کارن‌سیر<small>اکوسیستم هوشمند سفر و رفاه</small></span></Link> }
function Header(){ return <header className="site-header"><div className="header"><Brand/><nav aria-label="ناوبری اصلی">{nav.slice(0,5).map(([n,p])=><Link href={p} key={p}>{n}</Link>)}</nav><div className="header-actions"><Link className="support-link" href="/assistant">پشتیبانی سفر</Link><Link className="ghost" href="/login">ورود / ثبت‌نام</Link></div></div></header> }
function MobileNav(){ return <nav className="mobile-nav">{nav.slice(0,5).map(([n,p])=><Link href={p} key={p}>{n}</Link>)}</nav> }
function Footer(){return <footer className="footer"><div className="footer-main"><div><Brand/><p>همه‌ی سفر، رفاه و تجربه‌های مقصد در یک مسیر شفاف و قابل اعتماد.</p><span className="mock-label">داده‌های نمایشی · Mock</span></div><div><strong>خدمات سفر</strong><Link href="/hotels">هتل و اقامتگاه</Link><Link href="/compare">مقایسه گزینه‌ها</Link><Link href="/assistant">دستیار هوشمند</Link></div><div><strong>راهکارهای کسب‌وکار</strong><Link href="/organization">خدمات سازمانی</Link><Link href="/white-label">وایت‌لیبل</Link><Link href="/integrations">تأمین‌کنندگان</Link></div><div><strong>همراه شما</strong><span>پشتیبانی سفر</span><span>۰۲۱-۹۱۰۰ ۷۱۰۰</span><span>hello@karenseir.ir</span></div></div><div className="footer-bottom"><span>© ۱۴۰۵ کارن‌سیر؛ همه حقوق محفوظ است.</span><span>حریم خصوصی · قوانین استفاده</span></div></footer>}
export function Shell({children}:{children:React.ReactNode}){ return <><Header/><main>{children}</main><MobileNav/><Footer/></> }
function Hero(){ return <section className="hero"><div className="hero-copy"><span className="eyebrow light">سفر را همان‌طور که دوست داری تجربه کن</span><h1>از رؤیای سفر تا<br/><em>خاطره‌ای ماندگار</em></h1><p>پرواز، اقامت، تجربه‌های مقصد و مزایای سازمانی؛ همه در یک اکوسیستم هوشمند و همراه.</p><div className="hero-actions"><a className="button aqua" href="#search">سفرت را شروع کن</a><Link className="button glass" href="/assistant">✦ دستیار هوشمند سفر</Link></div><div className="hero-trust"><span>✓ مسیر پشتیبانی روشن</span><span>✓ مقایسه شفاف</span><span>✓ پرداخت پس از اتصال معتبر</span></div></div><div className="hero-image"><Image src="/images/home/hero-yazd.png" alt="معماری یزد و مسافر" fill priority sizes="(max-width: 900px) 100vw, 54vw"/><div className="floating-card"><span>پیشنهاد امروز · Mock</span><strong>قشم، از ۷٬۴۵۰٬۰۰۰ تومان</strong><small>۴ روز و ۳ شب · امتیاز ۴٫۹</small></div></div></section> }
function HotelCard({hotel, compact=false}:{hotel:typeof hotels[number]; compact?:boolean}){return <article className={'hotel-card '+(compact?'compact':'')}><Image src={hotel.image} width={1200} height={800} sizes={compact?'220px':'(max-width: 600px) 255px, 33vw'} alt={hotel.name}/><div className="hotel-info"><div className="card-top"><span className="tag">{hotel.tag}</span><span>★ {hotel.score}</span></div><h3>{hotel.name}</h3><p>{hotel.city} · اتاق دوتخته · صبحانه</p><div className="card-bottom"><span><b>{hotel.price}</b> ریال<small>هر شب · Mock</small></span><span className="hotel-actions"><Link href="/compare" className="text-link">مقایسه</Link><Link href="/booking/confirmation" className="text-link">رزرو Mock ←</Link></span></div></div></article>}
const trips=[
 {title:'سه روز در شیراز',meta:'۳ روز و ۲ شب',price:'۶٬۹۰۰٬۰۰۰',score:'۴٫۷',image:'/images/figma/trip-shiraz.jpeg'},
 {title:'آرامش در جزیره قشم',meta:'۴ روز و ۳ شب',price:'۷٬۴۵۰٬۰۰۰',score:'۴٫۹',image:'/images/figma/trip-qeshm.jpeg'},
 {title:'مسیر سبز شمال',meta:'۳ روز و ۲ شب',price:'۵٬۲۵۰٬۰۰۰',score:'۴٫۵',image:'/images/figma/trip-north.jpeg'}
];
const experiences:Array<[string,string,string,string]>=[['رستوران و کافه','طعم‌های منتخب هر شهر','♨','/restaurants'],['رویداد و تالار','لحظه‌های به‌یادماندنی','◇','/events-venues'],['استخر و ورزش','تندرستی در سفر','◌','/pools-sports'],['اماکن گردشگری و تفریحی','جاذبه‌های هر مقصد','⌖','/attractions']];
function SectionTitle({kicker,title,copy,link}:{kicker:string;title:string;copy?:string;link?:string}){return <div className="section-title"><div><span className="eyebrow">{kicker}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>{link&&<Link href={link}>مشاهده همه ←</Link>}</div>}
function Trips(){return <section className="section container" id="offers"><SectionTitle kicker="پیشنهادهای ویژه" title="سفرهای انتخاب‌شده برای تو" copy="ترکیبی از مقصد، اقامت و تجربه؛ با داده‌های نمایشی شفاف." link="/hotels"/><div className="trip-grid">{trips.map(t=><article className="trip-card" key={t.title}><Image src={t.image} width={1280} height={640} sizes="(max-width: 600px) 82vw, (max-width: 900px) 33vw, 380px" alt={`نمایی از ${t.title}`}/><div><span className="mock-label">پکیج Mock</span><h3>{t.title}</h3><p>{t.meta}</p><strong>شروع از {t.price} تومان</strong><footer><span>★ {t.score}</span><Link href="/compare" aria-label={`مقایسه ${t.title}`}>←</Link></footer></div></article>)}</div></section>}
function SmartFeatures(){return <section className="smart-section"><div className="container smart-grid"><div className="assistant-showcase"><span className="spark">✦</span><span className="eyebrow light">همراه هوشمند کارن‌سیر</span><h2>یک سفر خوب، از یک گفت‌وگوی خوب شروع می‌شود.</h2><p>بودجه، علایق و محدودیت‌هایت را بگو؛ دستیار سفر گزینه‌های Mock را کنار هم می‌چیند و دلیل هر پیشنهاد را شفاف نشان می‌دهد.</p><div className="mini-chat"><span>برای یک سفر آرام سه‌روزه کجا پیشنهاد می‌کنی؟</span><b>یزد و کاشان، با دو سبک متفاوت…</b></div><Link className="button aqua" href="/assistant">گفت‌وگو با دستیار</Link></div><div className="compare-showcase"><span className="eyebrow">مقایسه هوشمند</span><h2>بهترین گزینه، فقط ارزان‌ترین نیست.</h2><p>قیمت، کیفیت، امکانات، قوانین کنسلی و policy سازمانی را یک‌جا ببین.</p><div className="compare-mini"><div><span>هتل زندیه</span><b>۹۲</b><i style={{width:'92%'}}/></div><div><span>پارسیان آزادی</span><b>۸۶</b><i style={{width:'86%'}}/></div><div><span>قصر طلایی</span><b>۸۱</b><i style={{width:'81%'}}/></div></div><Link className="text-link" href="/compare">شروع مقایسه ←</Link></div></div></section>}
function Experiences(){return <section className="section container" id="experiences"><SectionTitle kicker="فراتر از رزرو" title="مقصد را زندگی کن" copy="از میز شام تا یک راهنمای محلی؛ تجربه سفر جایی بیرون از اتاق هتل کامل می‌شود."/><div className="experience-grid">{experiences.map(x=><article key={x[0]}><span>{x[2]}</span><h3>{x[0]}</h3><p>{x[1]}</p><Link href="/assistant">کشف تجربه‌ها ←</Link></article>)}</div></section>}
function OrganizationFeature(){return <section className="organization-feature"><div className="container org-grid"><div><span className="eyebrow light">کارن‌سیر برای سازمان‌ها</span><h2>رفاه کارکنان، ساده برای آن‌ها؛ شفاف برای شما.</h2><p>اعتبار سفر، کیف پول، اقساط، مزایای رفاهی و گردش تأیید را با سیاست‌های tenant-aware مدیریت کنید؛ بدون اتصال نمایشی به پرداخت یا provider واقعی.</p><div className="org-actions"><Link href="/organization" className="button warm">راهکار سازمانی</Link><Link href="/white-label" className="button glass">وایت‌لیبل اختصاصی</Link></div></div><div className="wallet-card"><div className="wallet-head"><span>کیف پول رفاهی · Mock</span><b>کارن‌سیر سازمانی</b></div><small>اعتبار قابل استفاده</small><strong>۴۸٬۰۰۰٬۰۰۰ <em>ریال</em></strong><div className="wallet-stats"><span>سفر <b>۶۰٪</b></span><span>ورزش <b>۲۵٪</b></span><span>رویداد <b>۱۵٪</b></span></div><p>✓ منطبق با سیاست فعال سازمان</p></div></div></section>}
function Ecosystem(){return <section className="section container ecosystem" id="services"><SectionTitle kicker="یک حساب، یک تجربه یکپارچه" title="اکوسیستم کارن‌سیر چطور همراهت می‌ماند؟"/><div className="ecosystem-flow"><div><b>۱</b><span>کشف و برنامه‌ریزی</span><small>جست‌وجو و دستیار هوشمند</small></div><i>←</i><div><b>۲</b><span>مقایسه و انتخاب</span><small>قیمت، کیفیت و policy</small></div><i>←</i><div><b>۳</b><span>سفر و تجربه مقصد</span><small>اقامت، رویداد و خدمات محلی</small></div><i>←</i><div><b>۴</b><span>پشتیبانی و بازگشت</span><small>همراهی و کیف پول</small></div></div><div className="trust-row"><span><b>روشن</b> مسیر پشتیبانی</span><span><b>شفاف</b> مقایسه قابل توضیح</span><span><b>امن</b> اتصال fail-closed</span><span><b>یکپارچه</b> سفر و رفاه</span></div></section>}
function Partners(){return <section className="partners"><div className="container"><p>همراه کسب‌وکارهای سفر و رفاه</p><div><span>هتل‌ها</span><span>آژانس‌ها</span><span>راهنمایان</span><span>مجموعه‌های ورزشی</span><span>سازمان‌ها</span></div><Link href="/integrations">پیوستن به شبکه تأمین‌کنندگان ←</Link></div></section>}
const destinations=[
  {name:'قشم',caption:'جزیره شگفتی‌ها',image:'/images/figma/trip-qeshm.jpeg',className:'qeshm'},
  {name:'شیراز',caption:'شهر شعر و عطر بهارنارنج',image:'/images/figma/trip-shiraz.jpeg',className:'shiraz'},
  {name:'اصفهان',caption:'نصف جهان',image:'/images/home/hero-yazd.png',className:'isfahan'},
  {name:'ماسوله',caption:'خانه‌های رو به مه',image:'/images/figma/trip-north.jpeg',className:'masuleh'},
];
function HomeHeader(){return <header className="ref-header"><div className="ref-container"><Brand/><nav aria-label="ناوبری صفحه اصلی"><a href="#home-services">خدمات</a><Link href="/trips">سفرهای من</Link><Link href="/nearby?trip=mock-shiraz-1405">اطراف من</Link><Link href="/organization">سازمانی</Link></nav><div><Link href="/assistant" className="ref-help">پشتیبانی</Link><Link href="/login" className="ref-login">ورود / ثبت‌نام</Link></div></div></header>}
// Reuses the existing sitewide .mobile-nav bar/CSS (see MobileNav above) so the
// Homepage's own header links (HomeHeader, above - different targets than the
// generic Header's `nav` array) are reachable below ~800px too. HomeHeader's
// nav collapses to nothing at <=900px with no replacement, which was the
// reported mobile-navigation gap: خدمات/سفرهای من/اطراف من/سازمانی/پشتیبانی
// were unreachable on mobile with no menu button anywhere in the header.
function HomeMobileNav(){return <nav className="mobile-nav" aria-label="ناوبری صفحه اصلی (موبایل)"><a href="#home-services">خدمات</a><Link href="/trips">سفرهای من</Link><Link href="/nearby?trip=mock-shiraz-1405">اطراف من</Link><Link href="/organization">سازمانی</Link><Link href="/assistant">پشتیبانی</Link></nav>}
function SearchResultsSlot(){
  // Renders the same UnifiedSearchView used at /search/results, inline,
  // directly beneath the Homepage search form - only once a real search has
  // been submitted (presence of `destination` in the URL is the same signal
  // HomeSearchExperience always sets). No second engine, no duplicated
  // logic: this is the exact same component, just embedded in place instead
  // of navigating to a separate route.
  const searchParams=useSearchParams();
  if(searchParams.get('destination')===null)return null;
  return <UnifiedSearchView embedded/>;
}
function ReferenceHero(){return <><section className="ref-hero"><Image src="/images/home/hero-yazd.png" fill priority sizes="100vw" alt="مسافری در میان بادگیرها و معماری خشتی یزد"/><div className="ref-hero-shade"/><div className="ref-hero-copy"><span>ایران را دوباره کشف کن</span><h1>سفر را<br/><em>زندگی کن</em></h1><p>هر مقصد، قصه‌ای تازه است؛ قصه‌ای که با کارن‌سیر از همین‌جا آغاز می‌شود.</p></div><div className="ref-hero-stamp"><b>یزد</b><span>شهر بادگیرها</span></div></section><div className="ref-search-shell"><Suspense fallback={null}><HomeSearchExperience/></Suspense><Suspense fallback={null}><SearchResultsSlot/></Suspense><div className="search-human-help"><span><b>نیاز به راهنمایی داری؟</b><small>کارشناس انسانی، جدا از دستیار هوشمند</small></span><Link href="/support?channel=expert">صحبت با کارشناس</Link></div></div></>}
const homeServiceGroups=[['✓','قبل از سفر','بیمه، ویزا، CIP و آماده‌سازی'],['↔','جابه‌جایی','خودرو، ترانسفر و حمل‌ونقل'],['⌂','اقامت','هتل، اقامتگاه و بوم‌گردی'],['♨','رستوران و غذا','رستوران، کافه و غذای مقصد'],['◇','تفریح و تجربه','گشت، راهنما، ورزش و رویداد'],['✣','خرید سفر','صنایع‌دستی، سوغات و ملزومات']];
function HomeServicesHub(){return <section className="home-services-hub" id="home-services"><div className="ref-container"><header><div><span>خدماتی برای تمام مسیر سفر</span><h2>خدمات کارن‌سیر</h2><p>ابزارها و محصولات قابل اقدام؛ جدا از مقصدهای الهام‌بخش.</p></div><Link href="/services">مشاهده همه خدمات ←</Link></header><div>{homeServiceGroups.map((item,i)=><Link href={`/services?group=${i}`} key={item[1]}><i>{item[0]}</i><span><b>{item[1]}</b><small>{item[2]}</small></span><em>مشاهده ←</em></Link>)}</div><footer><span className="home-credit-symbol">ک</span><p><b>اعتبارپذیر</b> یعنی امکان بررسی اعتبار شخصی یا سازمانی؛ مانده و مجوز مصرف فقط از سامانه معتبر می‌آید.</p></footer></div></section>}
function DestinationMosaic(){return <section className="ref-section ref-container" id="destinations"><div className="ref-heading"><div><span>مقصد بعدی تو کجاست؟</span><h2>ایران، پر از جاهای دیدنی</h2></div><Link href="/assistant">همه مقصدها ←</Link></div><div className="destination-mosaic">{destinations.map(d=><Link href="/assistant" className={`destination-tile ${d.className}`} key={d.name}><Image src={d.image} fill sizes="(max-width: 700px) 100vw, 50vw" alt={`نمایی از ${d.name}`}/><span><b>{d.name}</b><small>{d.caption}</small></span></Link>)}</div></section>}
function ReferenceTrips(){return <section className="ref-section selected-section" id="selected-trips"><div className="ref-container"><div className="ref-heading"><div><span>پیشنهادهای کارن‌سیر</span><h2>سفرهای انتخاب‌شده برای تو</h2></div><Link href="/hotels">مشاهده همه ←</Link></div><div className="ref-trip-grid">{trips.map((t,i)=><article className="ref-trip" key={t.title}><Image src={t.image} width={1280} height={640} sizes="(max-width: 700px) 86vw, 33vw" alt={`نمایی از ${t.title}`}/><div><span className="ref-mock">پیشنهاد Mock</span><h3>{t.title}</h3><p>{t.meta} · {['اقامت و صبحانه','اقامت و گشت محلی','اقامت و طبیعت‌گردی'][i]}</p><div className="trip-fit"><span>{['مناسب سفر دونفره','مناسب خانواده','مناسب آرامش'][i]}</span><span>قوانین شفاف</span></div><strong>از {t.price} تومان</strong><small className="trip-supplier">ارائه‌دهنده و موجودی پس از اتصال معتبر نمایش داده می‌شود.</small><footer><span>★ {t.score}</span><Link href="/compare" aria-label={`مقایسه ${t.title}`}>مقایسه ←</Link></footer></div></article>)}</div></div></section>}
function SmartCompanion(){const capabilities=['پیشنهاد مقصد متناسب با بودجه','برنامه‌ریزی سفر','مقایسه پرواز، هتل، پرواز + هتل و سایر خدمات','پیشنهاد گزینه‌های مناسب','راهنمایی قبل، حین و بعد از سفر'];return <section className="ref-section ref-container ai-travel-section" id="smart-companion" aria-labelledby="ai-travel-title"><div className="smart-banner"><div className="smart-portrait" aria-hidden="true"><span>AI</span><b>✦</b><small>هوش سفر کارن‌سیر</small></div><div className="ai-travel-copy"><span className="smart-kicker"><i>AI</i> همراه هوشمند سفر</span><h2 id="ai-travel-title">دستیار هوشمند سفر کارن‌سیر</h2><p>مقصد، بودجه و شرایطت را بگو؛ سفرت را هوشمندانه طراحی و مقایسه می‌کنم.</p><ul className="ai-capabilities">{capabilities.map(capability=><li key={capability}><span aria-hidden="true">✓</span>{capability}</li>)}</ul><Link href="/assistant" className="coral-button">شروع گفتگو با AI</Link></div></div></section>}
const compareOptions=[['هتل زندیه','۹۲','ارزش خرید بهتر','کنسلی منعطف'],['پارسیان آزادی','۸۶','موقعیت بهتر','امکانات بیشتر'],['قصر طلایی','۸۱','مناسب خانواده','اتاق بزرگ‌تر']];
function CompareBand(){return <section className="compare-band"><div className="ref-container"><div><span>قابلیت امضای کارن‌سیر</span><h2>قبل از انتخاب، کنار هم ببین.</h2><p>قیمت، کیفیت، امکانات، قوانین و ارزش واقعی را یک‌جا بفهم.</p></div><div className="compare-cards">{compareOptions.map(x=><article key={x[0]}><header><strong>{x[0]}</strong><b>{x[1]}</b></header><div><span>{x[2]}</span><span>{x[3]}</span></div></article>)}</div><Link href="/compare">شروع مقایسه ←</Link></div></section>}
function LocalExperiences(){return <section className="ref-section ref-container"><div className="ref-heading"><div><span>سفر فقط رسیدن نیست</span><h2>تجربه‌های مقصد را کامل کن</h2></div><Link href="/experiences">مشاهده همه تفریح و تجربه ←</Link></div><div className="ref-experiences">{experiences.map(x=><Link href={x[3]} key={x[0]}><i>{x[2]}</i><span><b>{x[0]}</b><small>{x[1]}</small></span><em>←</em></Link>)}</div></section>}
function ReferenceOrganization(){return <section className="ref-org"><div className="ref-container"><div className="org-art"><div className="org-window"><span>اعتبار رفاهی · Mock</span><b>۴۸٬۰۰۰٬۰۰۰ ریال</b><i><em style={{width:'68%'}}/></i><small>نمونه نمایشی؛ مانده واقعی از سامانه مجاز دریافت می‌شود.</small></div><div className="org-person">ک</div></div><div><span>کارن‌سیر برای سازمان‌ها</span><h2>حال خوب کارکنان،<br/>مدیریت ساده برای شما</h2><p>سفر، کیف پول، اقساط و مزایای رفاهی را با سیاست‌های شفاف و وایت‌لیبل اختصاصی در یک مسیر مدیریت کنید.</p><div className="org-value"><span><b>اعتبار سازمانی</b><small>پس از احراز و استعلام</small></span><span><b>سهم شخصی</b><small>شفاف پیش از پرداخت</small></span><span><b>گردش تأیید</b><small>قابل پیگیری برای کارمند</small></span></div><div><Link className="plum-button" href="/organization">خدمات سازمانی</Link><Link className="text-plum" href="/white-label">وایت‌لیبل اختصاصی ←</Link></div></div></div></section>}
const trustItems=[['⌁','مجوزها و اطلاعات ثبتی','فقط پس از دریافت و راستی‌آزمایی منتشر می‌شود.'],['§','قوانین و حقوق مسافر','شرایط، موارد شامل و مسیر پیگیری شفاف.'],['✓','پرداخت و بازگشت وجه','وضعیت نهایی فقط از سرویس مالی مجاز دریافت می‌شود.'],['◇','تأمین‌کننده و پشتیبانی','هویت ارائه‌دهنده و مسئولیت خدمت پیش از خرید.']];
function TrustSection(){return <section className="trust-section"><div className="ref-container"><div className="ref-heading"><div><span>اعتماد، بخشی از مسیر است</span><h2>با خیال راحت سفر کن</h2><p>ساختار حرفه‌ای برای مشاهده اسناد و حقوق مسافر؛ بدون نشان یا ادعای تأییدنشده.</p></div><Link href="/integrations">مرکز اطلاعات و همکاری ←</Link></div><div className="trust-grid">{trustItems.map(x=><article key={x[1]}><i aria-hidden="true">{x[0]}</i><div><h3>{x[1]}</h3><p>{x[2]}</p></div><span>اطلاعات تأییدشده در دسترس نیست</span></article>)}</div></div></section>}
function ServiceRibbon(){return <section className="service-ribbon" aria-label="فضای خدمات آینده"><div className="ref-container" aria-hidden="true"/></section>}
function ReferenceFooter(){return <footer className="ref-footer"><div className="ref-footer-curve"/><div className="ref-container ref-footer-grid"><div><Brand/><p>کارن‌سیر؛ از انتخاب مقصد تا تجربه و رفاه سازمانی، همراه تمام مسیر.</p><span className="ref-mock">تمام داده‌های مالی و موجودی Mock هستند</span></div><div><b>سفر با کارن‌سیر</b><Link href="/hotels">هتل و اقامتگاه</Link><Link href="/compare">مقایسه</Link><Link href="/assistant">همراه هوشمند</Link></div><div><b>راهکارها</b><Link href="/organization">سازمانی و رفاهی</Link><Link href="/white-label">وایت‌لیبل</Link><Link href="/integrations">همکاری با تأمین‌کنندگان</Link></div><div><b>همراه شما</b><span>۰۲۱-۹۱۰۰ ۷۱۰۰</span><span>پشتیبانی سفر</span><span>hello@karenseir.ir</span></div></div><div className="ref-container ref-footer-bottom"><span>© ۱۴۰۵ کارن‌سیر</span><span>قوانین استفاده · حریم خصوصی</span></div></footer>}
// On mobile the Homepage's hero + search widget together span nearly the
// entire viewport width and well past its height (measured: search widget
// alone ~520px tall in a ~780px-tall 430px-wide viewport, leaving no static
// corner clear of either the hero destination badge or the search form's
// controls - moving the button between corners just traded one real overlap
// for another, confirmed by measuring getBoundingClientRect() on both).
// Showing the button only once the user has scrolled past the search widget
// avoids the collision entirely, at any viewport height, without shrinking,
// redesigning, or repositioning the search widget itself.
function FloatingAssistant(){
  const [visible,setVisible]=useState(false);
  useEffect(()=>{
    function check(){const shell=document.querySelector('.ref-search-shell');const clearY=shell?shell.getBoundingClientRect().bottom+window.scrollY:600;setVisible(window.scrollY+window.innerHeight>clearY+40)}
    check();
    window.addEventListener('scroll',check,{passive:true});
    window.addEventListener('resize',check);
    return()=>{window.removeEventListener('scroll',check);window.removeEventListener('resize',check)};
  },[]);
  if(!visible)return null;
  return <Link className="mobile-ai-assistant" href="/assistant" aria-label="بازکردن دستیار هوشمند سفر"><span>AI</span> دستیار AI</Link>;
}
function Home(){return <div className="home-page"><HomeHeader/><main><ReferenceHero/><HomeServicesHub/><DestinationMosaic/><ReferenceTrips/><SmartCompanion/><CompareBand/><LocalExperiences/><ReferenceOrganization/><TrustSection/><ServiceRibbon/></main><HomeMobileNav/><ReferenceFooter/><FloatingAssistant/></div>}
function Hotels(){return <Shell><div className="page-hero"><span className="eyebrow">اقامت · داده نمایشی</span><h1>هتل را با معیارهای واقعی‌تر انتخاب کنید.</h1><p>قیمت و موجودی زیر صرفاً برای نمایش Prototype هستند و قابل رزرو واقعی نیستند.</p></div><div className="container results"><aside className="filters"><strong>فیلترها</strong>{['بازه قیمت','امتیاز مهمانان','سیاست سازمان','امکانات','قوانین کنسلی'].map(x=><button key={x}>{x}<span>⌄</span></button>)}</aside><section><div className="result-bar"><span>۳ گزینه Mock برای تهران</span><Link href="/compare" className="button primary">مقایسه ۳ گزینه</Link></div><div className="result-list">{hotels.map(h=><HotelCard hotel={h} compact key={h.name}/>)}</div></section></div></Shell>}
function Compare(){return <Shell><div className="page-hero"><span className="eyebrow">مقایسه حرفه‌ای · داده معتبر</span><h1>تفاوت‌ها را یک‌جا ببینید.</h1><p>امتیاز و معیارها فقط از Offerهای معتبر سازمان احرازشده محاسبه می‌شوند.</p></div><ConnectedCompare/></Shell>}
const policyIntents=['قوانین این رزرو چیه؟','می‌خوام کنسل کنم','چقدر پولم برمی‌گرده؟','می‌تونم تاریخ رو عوض کنم؟','هتلم رو کنسل کنم چقدر جریمه میشه؟','پروازم لغو شده','واچر جدیدم کجاست؟','درخواست استردادم چه وضعیتی داره؟'];
type AssistantMessage={role:'user'|'bot';text?:string;links?:boolean};
const assistantInitialMessages:AssistantMessage[]=[
  {role:'user',text:'می‌خوام رزرو رو کنسل کنم؛ چقدر پولم برمی‌گرده؟'},
  {role:'bot',text:'رزرو پرواز تهران به شیراز را پیدا کردم، اما مبلغ معتبر جریمه و بازگشت وجه در دسترس نیست: «نیاز به بررسی قوانین تأمین‌کننده».'},
  {role:'bot',links:true},
];
// This chat has no live backend (0 assistant routes; see CAPABILITY_REGISTRY.json
// ai_travel_assistant: NOT_STARTED) - previously the input was a plain <span>
// (not a real field) and "ارسال"/the intent chips had no handler at all, so
// nothing happened on click/type. Fixed to be genuinely interactive without
// fabricating an AI answer: every message - typed or a clicked example intent -
// is echoed back, and the reply is always the exact same honest
// no-live-provider-data fallback already shown in the static example above,
// consistent with how the rest of the app (e.g. "Provider زنده در دسترس نیست")
// discloses missing live data instead of inventing a number.
function Assistant(){
  const [messages,setMessages]=useState<AssistantMessage[]>(assistantInitialMessages);
  const [draft,setDraft]=useState('');
  function send(raw:string){
    const text=raw.trim();
    if(!text)return;
    setMessages(current=>[...current,{role:'user',text},{role:'bot',text:'رزرو فعال شما (KS-MOCK-2841) را در نظر گرفتم، اما بدون اتصال به قوانین معتبر تأمین‌کننده نمی‌توانم مبلغ دقیق جریمه یا بازگشت وجه را اعلام کنم: «نیاز به بررسی قوانین تأمین‌کننده».'},{role:'bot',links:true}]);
    setDraft('');
  }
  return <Shell><div className="assistant-page"><section className="assistant-intro"><span className="eyebrow">✦ دستیار هوشمند کارن‌سیر</span><h1>از تصمیم سفر تا<br/>مدیریت مشکل همراهت هستم.</h1><p>دستیار اطلاعات رزرو سفرت را در نظر می‌گیرد، اما بدون قوانین معتبر، جریمه یا مبلغ بازگشت را حدس نمی‌زند.</p><div className="assistant-steps"><span>برنامه‌ریزی و مقایسه</span><span>قوانین، تغییر و استرداد</span><span>اطراف من و پشتیبانی</span></div><div className="policy-intents" aria-label="نمونه پرسش‌های قابل فهم">{policyIntents.map(intent=><span key={intent} role="button" tabIndex={0} onClick={()=>send(intent)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();send(intent)}}}>{intent}</span>)}</div><Link className="assistant-booking-context" href="/manage-booking/book1">رزرو فعال: KS-MOCK-2841 · مدیریت رزرو ←</Link></section><section className="chat"><div className="chat-bar">دستیار قوانین و سفر <span>● نسخه نمایشی</span></div><div className="messages">{messages.map((message,index)=><div className={`message ${message.role}`} key={index}>{message.links?<><Link href="/manage-booking/book1">پیش‌نمایش مدیریت رزرو</Link> · <Link href="/support?channel=expert&booking=book1">ارسال برای بررسی کارشناس</Link></>:message.text}</div>)}</div><form className="chat-input" onSubmit={event=>{event.preventDefault();send(draft)}}><input value={draft} onChange={event=>setDraft(event.target.value)} placeholder="مثلاً: امکان تغییر تاریخ هست؟" aria-label="پیام به دستیار هوشمند" style={{flex:1,border:'none',outline:'none',background:'transparent',font:'inherit',color:'inherit'}}/><button type="submit">ارسال</button></form></section></div></Shell>}
function Organization(){return <Shell><div className="page-hero"><span className="eyebrow">داشبورد سازمانی</span><h1>ساختار و گردش تأیید سازمان</h1><p>نمای نقش‌محور با داده سازمان احرازشده.</p></div><ConnectedOrganization/></Shell>}
function Employee(){const {session}=useAuth();if(!session)return <Shell><ErrorState status={401} message="نشست مرورگر موجود نیست."/></Shell>;return <Shell><Dashboard title="سفر بعدی‌تان را هوشمندانه‌تر بچینید." subtitle="اعتبار و درخواست‌های شما در سازمان «بانک آفتاب» · Mock" employee/></Shell>}
function Dashboard({title,subtitle,tenant,employee}:{title:string;subtitle:string;tenant?:string;employee?:boolean}){return <div className="dashboard container"><div className="dashboard-title"><div><span className="eyebrow">{tenant?'داشبورد سازمانی':'داشبورد کارمند'}</span><h1>{title}</h1><p>{subtitle}</p></div><button className="button primary">{employee?'درخواست سفر جدید':'تعریف سیاست جدید'}</button></div><section className="metrics"><div><small>{employee?'اعتبار قابل مصرف':'بودجه تخصیص‌یافته'}</small><strong>{employee?'۴۸٬۰۰۰٬۰۰۰':'۳٬۲۰۰٬۰۰۰٬۰۰۰'} <em>ریال</em></strong><span>Mock · منبع server-side در محصول واقعی</span></div><div><small>{employee?'درخواست‌های من':'درخواست‌های در انتظار'}</small><strong>{employee?'۲':'۱۲'}</strong><span>{employee?'۱ نیازمند تأیید':'۶ مورد نزدیک به SLA'}</span></div><div><small>{employee?'سیاست فعال':'مصرف مطابق policy'}</small><strong>{employee?'سفر داخلی':'۹۴٪'}</strong><span>Mock</span></div></section><section className="dashboard-grid"><article className="panel"><div className="panel-head"><h3>{employee?'فعالیت‌های اخیر':'گردش تأیید'}</h3><span className="tag">Mock</span></div>{['اقامت تهران · در انتظار تأیید','تغییر سقف سفرهای داخلی','هتل زندیه · مطابق policy'].map((x,i)=><div className="activity" key={x}><span className={'status s'+i}></span><div><strong>{x}</strong><small>{i===0?'امروز، ۱۰:۲۵':'امروز، ۰۹:۴۰'}</small></div><button>مشاهده</button></div>)}</article><article className="panel"><div className="panel-head"><h3>{employee?'جزئیات اعتبار':'مصرف اعتبار براساس واحد'}</h3><span>Mock</span></div><div className="bar-list">{['فناوری','فروش','عملیات'].map((x,i)=><div key={x}><span>{x}</span><i><b style={{width:`${72-i*18}%`}}/></i><strong>{72-i*18}%</strong></div>)}</div></article></section></div>}
function WhiteLabel(){return <Shell><div className="white-label"><div className="wl-head"><span className="wl-logo">BA</span><div><strong>سفر و رفاه بانک آفتاب</strong><small>با زیرساخت کارن‌سیر · Prototype</small></div><button>ورود کارکنان</button></div><div className="wl-hero"><span>پرتال اختصاصی کارکنان</span><h1>از اعتبار رفاهی‌تان،<br/>با خیال آسوده استفاده کنید.</h1><p>قوانین و پیشنهادها متناسب با سیاست سازمان شما نمایش داده می‌شود.</p><Link href="/employee">مشاهده اعتبار من ←</Link></div><div className="wl-cards"><div>اعتبار سفر <b>Mock · نامشخص</b></div><div>درخواست‌های باز <b>۲ مورد Mock</b></div><div>پشتیبانی سازمانی <b>مسیر نمونه</b></div></div></div></Shell>}
function Integrations(){return <Shell><ConnectedRolePanel kind="backoffice"/></Shell>}
export default function Page(){
  const pathname=usePathname();
  if(pathname==='/hotels') return <Hotels/>;
  if(pathname==='/compare') return <Compare/>;
  if(pathname==='/assistant') return <Assistant/>;
  if(pathname==='/organization') return <Organization/>;
  if(pathname==='/employee') return <Employee/>;
  if(pathname==='/white-label') return <WhiteLabel/>;
  if(pathname==='/integrations') return <Integrations/>;
  return <Home/>;
}
