import type { CancellationQuote, NearbyPlace, NotificationPreference, PolicySnapshot, RefundRequest, Service, Trip, TripEvent, TripNotification } from './travel';

export const mockTrip:Trip={id:'mock-shiraz-1405',title:'سفر شیراز',origin:'تهران',destination:'شیراز',startDate:'۱۵ خرداد ۱۴۰۵',endDate:'۱۸ خرداد ۱۴۰۵',durationLabel:'۳ روز',status:'confirmed',stage:'before',travellers:[{id:'t1',fullName:'کاربر نمونه کارن‌سیر',type:'adult',documentHint:'اطلاعات هویتی Mock'},{id:'t2',fullName:'هم‌سفر نمونه',type:'adult',documentHint:'اطلاعات هویتی Mock'}],segments:[{id:'seg1',mode:'flight',origin:'تهران',destination:'شیراز',departure:'۱۵ خرداد · ۰۸:۴۰',arrival:'۱۵ خرداد · ۱۰:۱۰',carrierLabel:'پرواز نمونه · Provider متصل نیست'}],bookings:[{id:'book1',type:'transport',serviceType:'flight',title:'پرواز تهران به شیراز',status:'confirmed',supplierLabel:'تأمین‌کننده Mock',reference:'KS-MOCK-2841',disruptionStatus:'reported'},{id:'book2',type:'accommodation',serviceType:'hotel',title:'اقامت سه‌شب شیراز',status:'pending',supplierLabel:'فاقد Provider واقعی',reference:'در انتظار انتخاب',disruptionStatus:'none'}],vouchers:[{id:'voucher1',bookingId:'book1',status:'issued',title:'واچر نمایشی پرواز',issuedAt:'۱۲ خرداد ۱۴۰۵'}],itinerary:[{id:'i1',stage:'before',dateLabel:'۱۲ خرداد',title:'واچر آماده شد',detail:'نسخه نمایشی برای QA؛ قابل استفاده واقعی نیست.',status:'done'},{id:'i2',stage:'before',dateLabel:'پیش از حرکت',title:'تغییر تأمین‌کننده را بررسی کن',detail:'یک disruption نمونه ثبت شده و هنوز توسط Provider تأیید نشده است.',status:'upcoming'},{id:'i3',stage:'during',dateLabel:'روز ورود',title:'دسترسی سریع به اطراف اقامت',detail:'رستوران، حمل‌ونقل و تجربه‌های نزدیک را ببین.',status:'upcoming'},{id:'i4',stage:'after',dateLabel:'پس از بازگشت',title:'رسیدها و بازخورد',detail:'رزروهای تکمیل‌شده و بازخورد در یک محل.',status:'optional'}],accommodation:{name:'هنوز انتخاب نشده',address:'پس از رزرو معتبر نمایش داده می‌شود',checkIn:'۱۵ خرداد',checkOut:'۱۸ خرداد',status:'pending'},organizationContext:{tenantLabel:'سازمان نمونه',eligibilityStatus:'unknown',authoritative:false}};

export const mockPolicyAtBooking:PolicySnapshot={id:'policy-book1-at-booking',bookingId:'book1',version:'snapshot-mock-v1',capturedAt:'۱۲ خرداد ۱۴۰۵',sourceLabel:'snapshot نمایشی زمان رزرو',serviceType:'flight',cancellation:{availability:'verification-required',refundable:'unknown',penaltyBasis:'براساس قوانین تأمین‌کننده در زمان رزرو',providerVerificationRequired:true},refund:{availability:'verification-required',route:'unknown',processingLabel:'پس از تأیید تأمین‌کننده مشخص می‌شود',partialRefundSupported:'unknown'},change:{availability:'verification-required',supportedChanges:['date','route','name-correction'],providerVerificationRequired:true},noShow:{availability:'verification-required',consequenceLabel:'نیاز به بررسی rule ثبت‌شده زمان رزرو'},disruption:{availability:'verification-required',replacementSupported:'unknown',refundSupported:'unknown'}};
export const mockCurrentPolicy:PolicySnapshot={...mockPolicyAtBooking,id:'policy-book1-current',version:'current-unverified',capturedAt:'اکنون · بدون استعلام',sourceLabel:'Provider متصل نیست'};
export const mockCancellationQuote:CancellationQuote={id:'quote-cancel-book1',bookingId:'book1',caseType:'voluntary',eligibility:'unknown',policyAvailability:'verification-required',currency:'IRR',refundRoute:'unknown',providerVerificationRequired:true,explanation:'نیاز به بررسی قوانین تأمین‌کننده؛ جریمه و مبلغ قابل استرداد هنوز قابل محاسبه نیست.',mock:true};
export const mockHotelPolicyAtBooking:PolicySnapshot={id:'policy-book2-at-booking',bookingId:'book2',version:'hotel-snapshot-mock-v1',capturedAt:'نمونه زمان انتخاب',sourceLabel:'snapshot اقامت Mock',serviceType:'hotel',cancellation:{availability:'verification-required',refundable:'unknown',freeCancellationDeadline:undefined,penaltyBasis:'فاصله تا check-in و rule تأمین‌کننده',noShowRule:'نیازمند بررسی Provider',providerVerificationRequired:true},refund:{availability:'verification-required',route:'unknown',processingLabel:'پس از تأیید اقامتگاه مشخص می‌شود',partialRefundSupported:'unknown'},change:{availability:'verification-required',supportedChanges:['date','room','guest-count','nights','late-arrival','early-checkout'],providerVerificationRequired:true},noShow:{availability:'verification-required',consequenceLabel:'قانون no-show معتبر موجود نیست'},disruption:{availability:'verification-required',replacementSupported:'unknown',refundSupported:'unknown'}};
export const mockHotelCurrentPolicy:PolicySnapshot={...mockHotelPolicyAtBooking,id:'policy-book2-current',version:'hotel-current-unverified',capturedAt:'اکنون · بدون استعلام',sourceLabel:'اقامتگاه متصل نیست'};
export const mockHotelCancellationQuote:CancellationQuote={id:'quote-cancel-book2',bookingId:'book2',caseType:'voluntary',eligibility:'unknown',policyAvailability:'verification-required',currency:'IRR',refundRoute:'unknown',providerVerificationRequired:true,explanation:'refundable بودن، deadline، جریمه نزدیک check-in و مبلغ استرداد نیازمند بررسی قوانین اقامتگاه است.',mock:true};
export const mockRefundRequest:RefundRequest={id:'refund-request-mock-1',bookingId:'book1',caseType:'voluntary',quoteId:mockCancellationQuote.id,status:'reviewing',createdAt:'نمونه نمایشی',mock:true};

export const mockServices:Service[]=[
 {id:'s1',title:'بیمه سفر',category:'pre-trip',group:'before-trip',action:'انتخاب',description:'پوشش و شرایط فقط پس از اتصال بیمه‌گر معتبر.',destination:'شیراز',availability:'mock',creditCapability:'unknown'},
 {id:'s2',title:'ویزا و CIP',category:'pre-trip',group:'before-trip',action:'دریافت خدمت',description:'مسیر نمونه برای خدمات مدارک، CIP و آماده‌سازی.',availability:'mock',creditCapability:'unknown'},
 {id:'s3',title:'چک و امداد خودرو',category:'pre-trip',group:'before-trip',action:'مشاهده',description:'چک پیش از سفر و امداد از Provider معتبر آینده.',availability:'mock',creditCapability:'sample-enabled'},
 {id:'s4',title:'ترانسفر فرودگاه',category:'transfer',group:'mobility',action:'رزرو',description:'مسیر رفت‌وبرگشت با ارائه‌دهنده و policy شفاف.',destination:'شیراز',availability:'mock',creditCapability:'sample-enabled'},
 {id:'s5',title:'اجاره خودرو',category:'transfer',group:'mobility',action:'انتخاب',description:'خودرو، ودیعه و شرایط پس از استعلام Provider.',destination:'شیراز',availability:'mock',creditCapability:'unknown'},
 {id:'s6',title:'هتل و اقامتگاه',category:'essential',group:'stay',action:'رزرو',description:'اقامت سفر شیراز هنوز خریداری نشده است.',destination:'شیراز',availability:'mock',creditCapability:'sample-enabled'},
 {id:'s7',title:'رستوران و کافه',category:'food',group:'food',action:'مشاهده',description:'مکان عمومی و شریک نمونه با تفکیک روشن.',destination:'شیراز',availability:'live',href:'/restaurants',creditCapability:'sample-enabled'},
 {id:'s8',title:'گشت و راهنمای محلی',category:'experience',group:'experience',action:'انتخاب',description:'گشت شهری، جاذبه و راهنما با منبع روشن.',destination:'شیراز',availability:'mock',creditCapability:'unknown'},
 {id:'s9',title:'تفریح، ورزش و رویداد',category:'wellness',group:'experience',action:'مشاهده',description:'تفریح، استخر، ورزش، تالار و رویداد.',destination:'شیراز',availability:'live',href:'/experiences',creditCapability:'sample-enabled'},
 {id:'s10',title:'صنایع‌دستی و سوغات',category:'souvenir',group:'travel-commerce',action:'مشاهده',description:'تجارت مرتبط با سفر و مستقل از 60/70Online.',destination:'شیراز',availability:'mock',creditCapability:'unknown'},
 {id:'s11',title:'محصولات فرهنگی',category:'souvenir',group:'travel-commerce',action:'انتخاب',description:'محصولات مرتبط با مقصد با منشأ قابل بررسی.',destination:'شیراز',availability:'mock',creditCapability:'sample-enabled'},
 {id:'s12',title:'ملزومات سفر',category:'essential',group:'travel-commerce',action:'مشاهده',description:'لوازم کاربردی سفر؛ عرضه‌کننده واقعی متصل نیست.',availability:'mock',creditCapability:'unknown'}
];

export const mockPlaces:NearbyPlace[]=[{id:'p1',name:'رستوران نمونه نارنجستان',category:'رستوران',distanceLabel:'۷۰۰ متر',openState:'unknown',sourceLabel:'فهرست Mock کارن‌سیر',latitude:29.615,longitude:52.535,merchant:{id:'m1',name:'رستوران نمونه نارنجستان',category:'food',relation:'contracted',benefit:{id:'b1',label:'مزیت نمونه',kind:'perk',mock:true}}},{id:'p2',name:'کافه نمونه باغ',category:'کافه',distanceLabel:'۱٫۲ کیلومتر',openState:'unknown',sourceLabel:'پذیرنده اعتباری Mock',latitude:29.61,longitude:52.53,merchant:{id:'m2',name:'کافه نمونه باغ',category:'food',relation:'credit-enabled',benefit:{id:'b2',label:'اعتبارپذیر',kind:'credit',mock:true}}},{id:'p3',name:'باغ عمومی نمونه',category:'دیدنی‌ها',distanceLabel:'۲ کیلومتر',openState:'unknown',sourceLabel:'مکان عمومی از MockPlaceProvider',latitude:29.62,longitude:52.54}];

export const mockNotifications:TripNotification[]=[{id:'n1',tripId:mockTrip.id,stage:'before',title:'رزرو شما قطعی شد',body:'سفر شیراز شما آماده است.',deepLink:`/trips/${mockTrip.id}`,kind:'booking'},{id:'n2',tripId:mockTrip.id,stage:'before',title:'واچر نمایشی صادر شد',body:'برای مشاهده واچر وارد سفر من شوید.',deepLink:`/trips/${mockTrip.id}#voucher`,kind:'voucher'},{id:'n3',tripId:mockTrip.id,stage:'before',title:'یک اقدام باقی مانده',body:'برای سفر شیراز هنوز ترانسفر انتخاب نکرده‌اید.',deepLink:`/trips/${mockTrip.id}?stage=before`,kind:'reminder'},{id:'n4',tripId:mockTrip.id,stage:'before',title:'وضعیت درخواست تغییر کرد',body:'درخواست نمونه استرداد در حال بررسی است.',deepLink:'/manage-booking/book1',kind:'after-sales'},{id:'n5',tripId:mockTrip.id,stage:'during',title:'به شیراز خوش آمدید',body:'خدمات اطراف مقصد سفرتان را ببینید.',deepLink:`/nearby?trip=${mockTrip.id}`,kind:'arrival'}];

export const mockTripEvents:TripEvent[]=[
  {id:'event-flight-time',tripId:mockTrip.id,bookingId:'book1',type:'flight.schedule_changed',severity:'important',title:'ساعت پرواز تغییر کرد',message:'زمان جدید هنوز باید از منبع معتبر تأیید شود.',occurredAt:'۱۳ خرداد · ۱۰:۲۰',effectiveAt:'۱۵ خرداد',source:'provider',requiresAction:true,status:'pending-verification',deepLink:`/trips/${mockTrip.id}?event=event-flight-time`},
  {id:'event-voucher-issued',tripId:mockTrip.id,bookingId:'book1',type:'voucher.reissued',severity:'info',title:'واچر جدید صادر شد',message:'نسخهٔ جدید واچر در مدارک سفر در دسترس است.',occurredAt:'۱۳ خرداد · ۱۱:۴۵',source:'system',requiresAction:false,status:'verified',deepLink:`/trips/${mockTrip.id}?event=event-voucher-issued#voucher`},
  {id:'event-refund-review',tripId:mockTrip.id,bookingId:'book1',type:'refund.status_changed',severity:'info',title:'درخواست استرداد در حال بررسی است',message:'برای دیدن وضعیت کامل درخواست، مدیریت رزرو را باز کنید.',occurredAt:'۱۴ خرداد · ۰۹:۱۰',source:'system',requiresAction:false,status:'verified',deepLink:'/manage-booking/book1#request-status'},
];

export const mockNotificationPreferences:NotificationPreference[]=[
  {topic:'important-trip-changes',channels:{in_app:true,push:false,sms:false}},
  {topic:'booking-updates',channels:{in_app:true,push:false,sms:false}},
  {topic:'refund-change-updates',channels:{in_app:true,push:false,sms:false}},
  {topic:'support-messages',channels:{in_app:true,push:false,sms:false}},
];
