'use client';

import { useRouter } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { useAuth } from '../../lib/api/auth-context';

type Suggestion={id:string;title:string;subtitle:string;entity_type:string;city?:string;country?:string;code?:string;source:string};
type AutocompleteResponse={suggestions:Suggestion[]};
type TripType='round_trip'|'one_way'|'multi_city';
type Popover='origin'|'destination'|'dates'|'passengers'|null;

const services=[
  {name:'پرواز',icon:'✈',vertical:'flight',origin:true},
  {name:'هتل',icon:'⌂',vertical:'hotel',origin:false},
  {name:'تور + هتل',icon:'◉',vertical:'package',origin:true},
  {name:'تشریفات فرودگاه',icon:'◇',vertical:'tourist_transport',origin:false},
] as const;
const entityLabels:Record<string,string>={city:'شهر',airport:'فرودگاه',railway_station:'ایستگاه',hotel:'هتل',accommodation:'اقامتگاه',attraction:'جاذبه',poi:'مکان دیدنی'};

function EntityInput({kind,label,value,onChange,onSelect,open,setOpen,vertical}:{kind:'origin'|'destination';label:string;value:string;onChange:(value:string)=>void;onSelect:(item:Suggestion)=>void;open:boolean;setOpen:()=>void;vertical:string}){
  const {api}=useAuth();
  const [items,setItems]=useState<Suggestion[]>([]); const [loading,setLoading]=useState(false); const request=useRef(0);
  useEffect(()=>{if(!open||value.trim().length<2)return;const current=++request.current;const timer=window.setTimeout(async()=>{setLoading(true);try{const response=await api.publicGet<AutocompleteResponse>(`/search/autocomplete/public?q=${encodeURIComponent(value)}`);if(current===request.current)setItems(response.suggestions)}catch{if(current===request.current)setItems([])}finally{if(current===request.current)setLoading(false)}},180);return()=>window.clearTimeout(timer)},[api,open,value,vertical]);
  return <div className="search-field entity-field"><label><span>{label}</span><input aria-label={label} role="combobox" aria-expanded={open} aria-controls={`${kind}-suggestions`} autoComplete="off" value={value} onFocus={setOpen} onClick={setOpen} onChange={event=>{onChange(event.target.value);setOpen()}}/></label>{open&&<div className="search-popover autocomplete-popover" id={`${kind}-suggestions`} role="listbox" aria-label={`پیشنهادهای ${label}`}>{loading?<div className="suggestion-loading">در حال یافتن مقصد…</div>:items.length?<>{items.map(item=><button type="button" role="option" aria-selected="false" key={item.id} onClick={()=>onSelect(item)}><i aria-hidden="true">{item.entity_type==='airport'?'✈':item.entity_type==='city'?'⌖':'◇'}</i><span><b>{item.title}</b><small>{[entityLabels[item.entity_type]??item.entity_type,item.code,item.city||item.country].filter(Boolean).join(' · ')}</small></span></button>)}</>:<div className="suggestion-empty">حداقل دو حرف بنویس؛ شهر، فرودگاه یا کد IATA را جست‌وجو می‌کنیم.</div>}</div>}</div>
}

export function HomeSearchExperience(){
  const router=useRouter(); const [active,setActive]=useState(0); const service=services[active];
  const [origin,setOrigin]=useState('تهران'); const [destination,setDestination]=useState(service.vertical==='hotel'?'یزد':'شیراز');
  const [depart,setDepart]=useState('2026-09-15'); const [returnDate,setReturnDate]=useState('2026-09-18'); const [flexibility,setFlexibility]=useState('exact'); const [tripType,setTripType]=useState<TripType>('round_trip');
  const [adults,setAdults]=useState(2); const [children,setChildren]=useState(0); const [infants,setInfants]=useState(0); const [rooms,setRooms]=useState(1); const [cabin,setCabin]=useState('economy'); const [popover,setPopover]=useState<Popover>(null);
  function changeService(index:number){setActive(index);setPopover(null);const next=services[index];setDestination(next.vertical==='hotel'?'یزد':next.vertical==='package'?'قشم':next.vertical==='tourist_transport'?'فرودگاه امام خمینی':'شیراز')}
  function submit(){const params=new URLSearchParams({vertical:service.vertical,origin:service.origin?origin:'',destination,depart,trip_type:tripType,flexibility,adults:String(adults),children:String(children),infants:String(infants),rooms:String(rooms),cabin,sort:'recommended'});if(tripType==='round_trip')params.set('return',returnDate);router.push(`/search/results?${params.toString()}`)}
  const travellerTotal=adults+children+infants;
  return <section className="search-wrap" id="search" aria-label="جست‌وجوی یکپارچه سفر" onKeyDown={event=>{if(event.key==='Escape')setPopover(null)}}>
    <div className="service-tabs" role="tablist" aria-label="نوع خدمت">{services.map((tab,index)=><button type="button" role="tab" aria-selected={active===index} aria-controls="service-search-panel" onClick={()=>changeService(index)} className={active===index?'active':''} key={tab.name}><span aria-hidden="true">{tab.icon}</span>{tab.name}</button>)}</div>
    <div className="trip-type-row" aria-label="نوع سفر">{service.vertical==='flight'&&<>{([['round_trip','رفت‌وبرگشت'],['one_way','یک‌طرفه'],['multi_city','چندمسیره']] as const).map(([value,label])=><button type="button" aria-pressed={tripType===value} className={tripType===value?'active':''} onClick={()=>{if(value==='multi_city'){setTripType(value);router.push('/search/results?vertical=flight&trip_type=multi_city&edit=1')}else setTripType(value)}} key={value}>{label}</button>)}</>}</div>
    <div className={`search-card professional-search ${service.origin?'with-origin':'without-origin'}`} id="service-search-panel" role="tabpanel" aria-label={`فرم جست‌وجوی ${service.name}`}>
      {service.origin&&<><EntityInput kind="origin" label="مبدأ" value={origin} onChange={setOrigin} onSelect={item=>{setOrigin(item.title);setPopover(null)}} open={popover==='origin'} setOpen={()=>setPopover('origin')} vertical={service.vertical}/><button type="button" className="swap" aria-label="جابجایی مبدا و مقصد" onClick={()=>{setOrigin(destination);setDestination(origin)}}>⇄</button></>}
      <EntityInput kind="destination" label={service.vertical==='hotel'?'شهر، هتل یا جاذبه':'مقصد'} value={destination} onChange={setDestination} onSelect={item=>{setDestination(item.title);setPopover(null)}} open={popover==='destination'} setOpen={()=>setPopover('destination')} vertical={service.vertical}/>
      <div className="search-field"><button type="button" className="field-button" aria-expanded={popover==='dates'} onClick={()=>setPopover(popover==='dates'?null:'dates')}><span>تاریخ سفر</span><b>{depart.replaceAll('-','/')} {tripType==='round_trip'?`تا ${returnDate.replaceAll('-','/')}`:''}</b><small>{flexibility==='exact'?'تاریخ دقیق':flexibility==='plus_minus_1'?'±۱ روز':'±۳ روز'}</small></button>{popover==='dates'&&<div className="search-popover date-popover" aria-label="انتخاب تاریخ"><header><b>تاریخ سفر</b><small>قیمت فقط پس از اتصال داده معتبر نمایش داده می‌شود.</small></header><div><label><span>رفت</span><input aria-label="تاریخ رفت" type="date" value={depart} onChange={event=>setDepart(event.target.value)}/></label>{tripType==='round_trip'&&<label><span>برگشت</span><input aria-label="تاریخ برگشت" type="date" min={depart} value={returnDate} onChange={event=>setReturnDate(event.target.value)}/></label>}</div><fieldset><legend>تاریخ منعطف</legend>{[['exact','دقیق'],['plus_minus_1','±۱ روز'],['plus_minus_3','±۳ روز']].map(([value,label])=><button type="button" aria-pressed={flexibility===value} className={flexibility===value?'active':''} onClick={()=>setFlexibility(value)} key={value}>{label}</button>)}</fieldset><button type="button" className="popover-done" onClick={()=>setPopover(null)}>تأیید تاریخ</button></div>}</div>
      <div className="search-field"><button type="button" className="field-button" aria-expanded={popover==='passengers'} onClick={()=>setPopover(popover==='passengers'?null:'passengers')}><span>{service.vertical==='hotel'?'اتاق و مهمان':'مسافران'}</span><b>{travellerTotal.toLocaleString('fa-IR')} مسافر{service.vertical==='hotel'?`، ${rooms.toLocaleString('fa-IR')} اتاق`:''}</b><small>{service.vertical==='flight'?(cabin==='economy'?'اکونومی':'بیزینس'):'جزئیات مهمانان'}</small></button>{popover==='passengers'&&<div className="search-popover passenger-popover" aria-label="انتخاب مسافران">{([['بزرگسال','۱۲ سال به بالا',adults,setAdults,1],['کودک','۲ تا ۱۱ سال',children,setChildren,0],['نوزاد','کمتر از ۲ سال',infants,setInfants,0]] as const).map(([label,help,value,setter,min])=><div className="counter" key={label}><span><b>{label}</b><small>{help}</small></span><div><button type="button" aria-label={`کاهش ${label}`} disabled={value<=min} onClick={()=>setter(value-1)}>−</button><b>{value.toLocaleString('fa-IR')}</b><button type="button" aria-label={`افزایش ${label}`} onClick={()=>setter(value+1)}>+</button></div></div>)}{service.vertical==='hotel'&&<div className="counter"><span><b>اتاق</b><small>تعداد اتاق موردنیاز</small></span><div><button type="button" aria-label="کاهش اتاق" disabled={rooms<=1} onClick={()=>setRooms(rooms-1)}>−</button><b>{rooms.toLocaleString('fa-IR')}</b><button type="button" aria-label="افزایش اتاق" onClick={()=>setRooms(rooms+1)}>+</button></div></div>}{service.vertical==='flight'&&<label className="cabin-select"><span>کلاس پروازی</span><select aria-label="کلاس پروازی" value={cabin} onChange={event=>setCabin(event.target.value)}><option value="economy">اکونومی</option><option value="business">بیزینس</option></select></label>}<button type="button" className="popover-done" onClick={()=>setPopover(null)}>تأیید مسافران</button></div>}</div>
      <button type="button" className="button search-button" onClick={submit}>جست‌وجو</button>
    </div>
    <div className="search-tools"><span>قیمت و موجودی فقط از Provider معتبر</span><span>استعلام مجدد پیش از خرید</span></div>
  </section>
}
