'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { PartnerBadge } from './Badges';
import { ContextAssistant } from './ContextAssistant';
import type { NearbyPlace } from '../../lib/domain/travel';
const categories=['همه','رستوران','کافه','دیدنی‌ها','تفریح','خرید و سوغات','داروخانه','پمپ بنزین','حمل‌ونقل','خدمات ضروری'];
const contexts=['موقعیت فعلی من','اطراف محل اقامت من','اطراف مقصد سفر'];
export function NearbyExplorer({places}:{places:NearbyPlace[]}){const [category,setCategory]=useState('همه');const [context,setContext]=useState(2);const visible=useMemo(()=>places.filter(p=>category==='همه'||p.category===category),[category,places]);return <><section className="nearby-controls"><div><span>محدوده جست‌وجوی Mock</span>{contexts.map((x,i)=><button type="button" className={context===i?'active':''} onClick={()=>setContext(i)} key={x}>{x}</button>)}</div><small>{context===0?'Location واقعی درخواست نشده است.':context===1?'اقامت هنوز قطعی نیست؛ مرکز نمونه شیراز استفاده می‌شود.':'مرکز مقصد نمونه شیراز استفاده می‌شود.'}</small></section><div className="nearby-categories" role="tablist" aria-label="دسته‌بندی اطراف من">{categories.map(x=><button type="button" role="tab" aria-selected={category===x} className={category===x?'active':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><section className="nearby-layout"><div className="mock-map" aria-label="نقشه نمایشی شیراز"><div className="map-grid"/><span className="map-center">ک</span>{visible.map((place,i)=><i style={{right:`${25+i*24}%`,top:`${30+(i%2)*26}%`}} key={place.id}>{i+1}</i>)}<div className="map-label"><b>نمای نقشه Mock</b><small>بدون Google API یا موقعیت واقعی</small></div></div><div className="nearby-sheet"><header><div><span>{contexts[context]}</span><h2>{visible.length} نتیجه نمایشی</h2></div><small>مرتب‌سازی: فاصله</small></header>{visible.length===0?<div className="nearby-empty">برای این دسته هنوز داده نمونه نداریم.</div>:visible.map((place,i)=><article key={place.id}><b className="place-number">{i+1}</b><div><div className="place-title"><h3>{place.name}</h3>{place.merchant?<PartnerBadge relation={place.merchant.relation}/>:<PartnerBadge relation="external"/>}</div><p>{place.category} · {place.distanceLabel} · وضعیت بازبودن نامشخص</p><small>منبع: {place.sourceLabel}</small>{place.merchant?.benefit&&<em>{place.merchant.benefit.label} · Mock</em>}</div><button type="button" disabled>مسیر · غیرفعال</button></article>)}</div></section><div className="nearby-lower"><ContextAssistant stage="nearby"/><section className="credit-legend"><span className="credit-symbol">ک</span><div><h2>نشان اعتبار کارن‌سیر</h2><p>«اعتبارپذیر» یعنی امکان بررسی اعتبار شخصی یا سازمانی وجود دارد؛ مبلغ و اجازه مصرف فقط از backend معتبر می‌آید.</p><Link href="/employee">جزئیات اعتبار نمونه ←</Link></div></section></div></>}
