'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useAuth } from '../../lib/api/auth-context';
import { ApiError, newId } from '../../lib/api/karenseir-client';

type Profile={user_id:number;name:string;email:string;role:string;locale:string};
type Traveller={id:string;full_name:string;profile_reference?:string|null};
type Wallet={id:string;currency:string;available:number;reserved:number;consumed:number};
type Payment={id:string;reservation_id:string;status:string;amount:number;currency:string;captured_amount:number;refunded_amount:number;provider_connected:boolean};
type Reservation={id:string;booking_reference?:string|null;status:string;service_type:string};
type Preference={topic:string;channel:string;enabled:boolean};
type Installment={id:string;title:string;terms:Record<string,unknown>;status:string};
type Agreement={id:string;plan_id:string;reservation_id:string;principal_amount:number;total_payable:number;currency:string;status:string;schedule:Array<{number:number;amount:number;status:string}>};
type Invoice={id:string;reservation_id:string;invoice_number:string;total_amount:number;currency:string;status:string;issued_at:string};
type AccountData={profile:Profile;travellers:Traveller[];wallets:Wallet[];payments:Payment[];reservations:Reservation[];preferences:Preference[];installments:Installment[];agreements:Agreement[];invoices:Invoice[]};
const faMoney=(amount:number,currency='IRR')=>`${amount.toLocaleString('fa-IR')} ${currency==='IRR'?'ریال':currency}`;
const messageOf=(error:unknown)=>error instanceof ApiError?error.message:'خطای پیش‌بینی‌نشده رخ داد.';

export function CustomerAccount(){
  const {api,session}=useAuth();const [data,setData]=useState<AccountData|null>(null);const [error,setError]=useState<{status:number;message:string}|null>(null);const [notice,setNotice]=useState('');
  const [name,setName]=useState('');const [travellerName,setTravellerName]=useState('');
  async function fetchAccount(){const values=await Promise.all([api.get<Profile>('/me/profile'),api.get<Traveller[]>('/me/travellers'),api.get<Wallet[]>('/me/wallets'),api.get<Payment[]>('/me/payments'),api.get<Reservation[]>('/me/reservations'),api.get<Preference[]>('/me/notification-preferences'),api.get<Installment[]>('/me/installment-plans'),api.get<Agreement[]>('/me/installments'),api.get<Invoice[]>('/me/invoices')]);return {profile:values[0],travellers:values[1],wallets:values[2],payments:values[3],reservations:values[4],preferences:values[5],installments:values[6],agreements:values[7],invoices:values[8]}}
  async function load(){const next=await fetchAccount();setData(next);setName(next.profile.name);}
  useEffect(()=>{if(!session)return;let active=true;Promise.all([api.get<Profile>('/me/profile'),api.get<Traveller[]>('/me/travellers'),api.get<Wallet[]>('/me/wallets'),api.get<Payment[]>('/me/payments'),api.get<Reservation[]>('/me/reservations'),api.get<Preference[]>('/me/notification-preferences'),api.get<Installment[]>('/me/installment-plans'),api.get<Agreement[]>('/me/installments'),api.get<Invoice[]>('/me/invoices')]).then(values=>{if(!active)return;const next={profile:values[0],travellers:values[1],wallets:values[2],payments:values[3],reservations:values[4],preferences:values[5],installments:values[6],agreements:values[7],invoices:values[8]};setData(next);setName(next.profile.name)}).catch(e=>active&&setError({status:e instanceof ApiError?e.status:0,message:messageOf(e)}));return()=>{active=false}},[api,session]);
  async function act(action:()=>Promise<unknown>,success:string){setNotice('در حال ثبت امن…');try{await action();await load();setNotice(success)}catch(e){setNotice(messageOf(e))}}
  if(!session)return <State title="برای مشاهده حساب وارد شوید." detail="نشست مرورگر موجود نیست."/>;if(error)return <State title={error.status===403?'دسترسی این نقش کافی نیست.':'دریافت حساب انجام نشد.'} detail={error.message}/>;if(!data)return <State title="در حال دریافت حساب…" detail="اطلاعات معتبر از سامانه دریافت می‌شود."/>;
  async function saveProfile(e:FormEvent){e.preventDefault();await act(()=>api.put('/me/profile',{name,locale:'fa-IR'}),'پروفایل ذخیره شد.')}
  async function addTraveller(e:FormEvent){e.preventDefault();await act(()=>api.post('/me/travellers',{full_name:travellerName}), 'مسافر افزوده شد.');setTravellerName('')}
  return <div className="grid gap-6"><header className="dashboard-title"><div><span className="eyebrow">حساب متصل کارن‌سیر</span><h1>پروفایل، مسافران و امور مالی</h1><p>همه داده‌ها از سازمان و نشست احرازشده دریافت می‌شوند.</p></div></header>{notice&&<p role="status" className="rounded-xl bg-cyan-50 p-4 text-cyan-900">{notice}</p>}
  <section className="grid gap-4 lg:grid-cols-2"><form onSubmit={saveProfile} className="panel"><h2 className="text-xl font-black">پروفایل مشتری</h2><label className="mt-4 block text-sm font-bold">نام و نام خانوادگی<input className="mt-2 block w-full rounded-xl border p-3" value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></label><p className="mt-3 text-sm text-slate-600">{data.profile.email} · {data.profile.role}</p><button className="button primary mt-4">ذخیره پروفایل</button></form>
  <section className="panel"><h2 className="text-xl font-black">مسافران</h2>{data.travellers.length===0?<p className="mt-3 text-slate-500">مسافری ثبت نشده است.</p>:data.travellers.map(t=><div key={t.id} className="mt-3 flex items-center justify-between rounded-xl bg-slate-50 p-3"><b>{t.full_name}</b><button className="text-link" onClick={()=>act(()=>api.post(`/me/travellers/${t.id}/remove`,{}),'مسافر حذف شد.')}>حذف</button></div>)}<form onSubmit={addTraveller} className="mt-4 flex gap-2"><input aria-label="نام مسافر" className="min-w-0 flex-1 rounded-xl border p-3" value={travellerName} onChange={e=>setTravellerName(e.target.value)} required minLength={3}/><button className="button secondary">افزودن</button></form></section></section>
  <section className="grid gap-4 lg:grid-cols-2"><article className="panel"><h2 className="text-xl font-black">کیف پول</h2>{data.wallets.length===0?<><p className="mt-3 text-slate-500">کیف پول شخصی ایجاد نشده است.</p><button className="button primary mt-4" onClick={()=>act(()=>api.post('/me/wallets',{currency:'IRR'},newId()),'کیف پول ایجاد شد.')}>ایجاد کیف پول ریالی</button></>:data.wallets.map(w=><div key={w.id} className="mt-4 grid grid-cols-2 gap-3"><Metric label="قابل استفاده" value={faMoney(w.available,w.currency)}/><Metric label="رزروشده" value={faMoney(w.reserved,w.currency)}/><Metric label="مصرف‌شده" value={faMoney(w.consumed,w.currency)}/></div>)}</article>
  <article className="panel"><h2 className="text-xl font-black">اقساط سازمانی</h2>{data.agreements.map(x=><div key={x.id} className="mt-3 rounded-xl bg-slate-50 p-3"><b>{faMoney(x.total_payable,x.currency)}</b><small className="block">{x.status} · {x.schedule.length.toLocaleString('fa-IR')} قسط</small></div>)}{data.installments.length===0?<p className="mt-3 text-slate-500">طرح قسط فعال و مجاز برای این حساب وجود ندارد.</p>:data.installments.map(x=><div key={x.id} className="mt-3"><b>{x.title}</b><pre className="text-sm">{JSON.stringify(x.terms,null,2)}</pre>{data.reservations.filter(r=>!data.agreements.some(a=>a.reservation_id===r.id)).map(r=><button className="button secondary mt-2" key={r.id} onClick={()=>act(()=>api.post(`/reservations/${r.id}/installments?plan_id=${x.id}`,{},newId()),'درخواست اقساط ثبت شد.')}>درخواست برای {r.booking_reference||r.service_type}</button>)}</div>)}</article></section>
  <section className="panel"><h2 className="text-xl font-black">پرداخت‌ها</h2><p className="mt-1 text-sm text-slate-600">اتصال درگاه بدون credential معتبر موفقیت نمایش نمی‌دهد.</p>{data.payments.length===0?<p className="mt-3 text-slate-500">Payment Intent ثبت نشده است.</p>:data.payments.map(p=><div key={p.id} className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><span><b>{faMoney(p.amount,p.currency)}</b><small className="block">{p.status} · رزرو {p.reservation_id}</small></span>{['created','failed'].includes(p.status)&&<button className="button secondary" onClick={()=>act(()=>api.post(`/payments/${p.id}/initiate`,{}),'درخواست درگاه ثبت شد.')}>اتصال به درگاه</button>}</div>)}<div className="mt-4 flex flex-wrap gap-2">{data.reservations.filter(r=>!data.payments.some(p=>p.reservation_id===r.id)).map(r=><button key={r.id} className="button secondary" onClick={()=>act(()=>api.post(`/reservations/${r.id}/payment-intents`,{},newId()),'Payment Intent ایجاد شد.')}>ساخت پرداخت برای {r.booking_reference||r.service_type}</button>)}</div></section>
  <section className="panel"><h2 className="text-xl font-black">صورتحساب‌ها</h2>{data.invoices.length===0?<p className="mt-3 text-slate-500">صورتحساب صادرشده‌ای وجود ندارد.</p>:data.invoices.map(invoice=><div className="mt-3 rounded-xl bg-slate-50 p-3" key={invoice.id}><b>{invoice.invoice_number}</b><span className="block">{faMoney(invoice.total_amount,invoice.currency)} · {invoice.status}</span></div>)}</section>
  <section className="panel"><h2 className="text-xl font-black">ترجیحات اعلان</h2>{(['web','app','push','sms'] as const).map(channel=>{const current=data.preferences.find(p=>p.topic==='trip_changes'&&p.channel===channel)?.enabled??true;return <button type="button" role="switch" aria-checked={current} key={channel} className="mt-3 flex w-full items-center justify-between rounded-xl border p-3" onClick={()=>act(()=>api.put('/me/notification-preferences',{topic:'trip_changes',channel,enabled:!current}),'ترجیحات اعلان ذخیره شد.')}><span>تغییرات سفر · {channel}</span><b>{current?'فعال':'غیرفعال'}</b></button>})}</section></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><small>{label}</small><b className="block">{value}</b></div>}
function State({title,detail}:{title:string;detail:string}){return <section role="status" className="mx-auto my-8 max-w-3xl rounded-2xl border bg-white p-8 text-center"><h2 className="text-xl font-black">{title}</h2><p className="mt-2 text-slate-600">{detail}</p></section>}

export function SupportComposer({reservationId}:{reservationId:string}){
  type Case={id:string;subject:string;status:string;priority:string;messages:Array<{id:string;sender_type:'customer'|'human_agent'|'ai'|'system';body:string;created_at:string}>};
  const {api,session}=useAuth();const [body,setBody]=useState('');const [subject,setSubject]=useState('بررسی رزرو');const [notice,setNotice]=useState('');const [cases,setCases]=useState<Case[]|null>(null);
  useEffect(()=>{if(!session)return;let active=true;api.get<Case[]>('/support/cases').then(rows=>active&&setCases(rows)).catch(error=>active&&setNotice(messageOf(error)));return()=>{active=false}},[api,session]);
  async function submit(event:FormEvent){event.preventDefault();setNotice('در حال ثبت پرونده…');try{await api.post('/support/cases',{reservation_id:reservationId,subject,body,priority:'normal'},newId());setBody('');setCases(await api.get<Case[]>('/support/cases'));setNotice('پرونده پشتیبانی انسانی ثبت شد.')}catch(error){setNotice(messageOf(error))}}
  if(!session)return <State title="برای ارسال پیام وارد شوید." detail="نشست مرورگر موجود نیست."/>;
  return <div className="grid gap-5"><section className="panel"><span className="eyebrow">پشتیبانی انسانی · پرونده سفر</span><h1 className="mt-2 text-2xl font-black">درخواست بررسی رزرو</h1><p className="mt-2 text-slate-600">پیام با رزرو متعلق به همین حساب و سازمان ثبت می‌شود؛ پیام AI جداگانه برچسب می‌خورد.</p><form className="mt-5" onSubmit={submit}><label className="font-bold">موضوع<input className="mt-2 block w-full rounded-xl border p-3" value={subject} onChange={e=>setSubject(e.target.value)} required minLength={3}/></label><label className="mt-3 block font-bold">شرح درخواست<textarea aria-label="شرح درخواست" className="mt-2 block min-h-32 w-full rounded-xl border p-3" value={body} onChange={e=>setBody(e.target.value)} required minLength={3}/></label><button className="button primary mt-4">ایجاد پرونده انسانی</button></form>{notice&&<p role="status" className="mt-4 rounded-xl bg-cyan-50 p-4">{notice}</p>}</section><section className="panel"><h2 className="text-xl font-black">رشته پیام‌ها</h2>{cases===null?<p>در حال دریافت پرونده‌ها…</p>:cases.length===0?<p>پرونده‌ای وجود ندارد.</p>:cases.map(item=><article className="mt-4 rounded-xl border p-4" key={item.id}><b>{item.subject} · {item.status}</b>{item.messages.map(message=><div className={`mt-3 rounded-xl p-3 ${message.sender_type==='human_agent'?'bg-emerald-50':message.sender_type==='ai'?'bg-violet-50':'bg-slate-50'}`} key={message.id}><strong>{message.sender_type==='human_agent'?'کارشناس انسانی':message.sender_type==='ai'?'دستیار هوشمند':message.sender_type==='system'?'سیستم':'مشتری'}</strong><p>{message.body}</p></div>)}</article>)}</section></div>
}
