'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { useAuth } from '../../lib/api/auth-context';
import { ApiError } from '../../lib/api/karenseir-client';

type SavedItem={id:string;service_type:string;source_reference:string;state:'wishlist'|'basket';snapshot:Record<string,unknown>};
type SavedTrip={id:string;title:string;status:string;items:SavedItem[]};
type ItineraryItem={id:string;title:string;service_type:string;day_number:number;position:number;availability_state:string};
type Itinerary={id:string;title:string;budget_amount?:number|null;status:string;items:ItineraryItem[]};
type Destination={id:string;slug:string;name_fa:string;name_en?:string;kind:string;description:string;geo:{latitude?:number|null;longitude?:number|null};service_counts:Record<string,number>};

function failure(error:unknown){return error instanceof ApiError?`${error.status}: ${error.message}`:'خطای پیش‌بینی‌نشده رخ داد.'}
function Gate({message}:{message:string}){return <section role="status" className="mx-auto my-8 max-w-4xl rounded-2xl border border-slate-200 bg-white p-7 text-center text-slate-600">{message}</section>}

export function SavedTravelView(){
  const {api,session}=useAuth();const [rows,setRows]=useState<SavedTrip[]|null>(null);const [notice,setNotice]=useState('');const [title,setTitle]=useState('');const [source,setSource]=useState('');
  async function load(){try{setRows(await api.get<SavedTrip[]>('/me/saved-trips'))}catch(error){setNotice(failure(error));setRows([])}}
  useEffect(()=>{if(!session)return;let active=true;api.get<SavedTrip[]>('/me/saved-trips').then(data=>{if(active)setRows(data)}).catch(error=>{if(active){setNotice(failure(error));setRows([])}});return()=>{active=false}},[api,session]);
  async function create(event:FormEvent){event.preventDefault();setNotice('در حال ذخیره امن…');try{await api.post('/saved-trips',{title,command_id:crypto.randomUUID()});setTitle('');setNotice('سفر ذخیره شد.');await load()}catch(error){setNotice(failure(error))}}
  async function add(event:FormEvent,trip:SavedTrip){event.preventDefault();try{await api.post(`/saved-trips/${trip.id}/items`,{service_type:'attraction',source_reference:source,state:'wishlist',command_id:crypto.randomUUID()});setSource('');setNotice('آیتم در علاقه‌مندی ذخیره شد.');await load()}catch(error){setNotice(failure(error))}}
  async function move(trip:SavedTrip,item:SavedItem,state:'wishlist'|'basket'){try{await api.put(`/saved-trips/${trip.id}/items/${item.id}`,{state,command_id:crypto.randomUUID()});setNotice(state==='basket'?'به سبد سفر منتقل شد.':'به علاقه‌مندی منتقل شد.');await load()}catch(error){setNotice(failure(error))}}
  async function remove(trip:SavedTrip,item:SavedItem){try{await api.delete(`/saved-trips/${trip.id}/items/${item.id}`,{command_id:crypto.randomUUID()});setNotice('آیتم حذف شد.');await load()}catch(error){setNotice(failure(error))}}
  if(!session)return <Gate message="برای مشاهده سبد سفر وارد شوید."/>;if(rows===null)return <Gate message="در حال دریافت سفرهای ذخیره‌شده…"/>;
  return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">Trip Basket</span><h1>سبد سفر و علاقه‌مندی‌ها</h1><p>هر سفر و آیتم فقط در tenant و حساب شما نگهداری می‌شود.</p></div></header>{notice&&<p role="status" className="mb-4 rounded-xl bg-cyan-50 p-4">{notice}</p>}<form onSubmit={create} className="panel mb-5 flex flex-wrap gap-3"><label className="min-w-64 flex-1 font-bold">عنوان سفر<input className="mt-2 block w-full rounded-xl border p-3" value={title} onChange={e=>setTitle(e.target.value)} minLength={2} required/></label><button className="button primary self-end">ساخت سفر ذخیره‌شده</button></form>{rows.length===0?<Gate message="هنوز سفر ذخیره‌شده‌ای ندارید."/>:rows.map(trip=><section className="panel mb-5" key={trip.id}><h2 className="text-xl font-black">{trip.title}</h2><form className="mt-3 flex gap-2" onSubmit={event=>add(event,trip)}><input aria-label={`مرجع آیتم ${trip.title}`} className="flex-1 rounded-xl border p-3" value={source} onChange={e=>setSource(e.target.value)} minLength={2} placeholder="مرجع Offer یا خدمت" required/><button className="button secondary">ذخیره در علاقه‌مندی</button></form>{trip.items.length===0?<p className="mt-3 text-slate-500">این سفر هنوز آیتمی ندارد.</p>:trip.items.map(item=><article className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4" key={item.id}><span><b>{item.source_reference}</b><small className="block">{item.service_type} · {item.state==='basket'?'سبد سفر':'علاقه‌مندی'}</small></span><span className="flex gap-2"><button className="button secondary" onClick={()=>move(trip,item,item.state==='basket'?'wishlist':'basket')}>انتقال</button><button className="button secondary" onClick={()=>remove(trip,item)}>حذف</button></span></article>)}</section>)}</div>
}

export function ItineraryView(){
  const {api,session}=useAuth();const [rows,setRows]=useState<Itinerary[]|null>(null);const [title,setTitle]=useState('');const [notice,setNotice]=useState('');
  async function load(){try{setRows(await api.get<Itinerary[]>('/me/itineraries'))}catch(error){setNotice(failure(error));setRows([])}}useEffect(()=>{if(!session)return;let active=true;api.get<Itinerary[]>('/me/itineraries').then(data=>{if(active)setRows(data)}).catch(error=>{if(active){setNotice(failure(error));setRows([])}});return()=>{active=false}},[api,session]);
  async function create(event:FormEvent){event.preventDefault();try{await api.post('/itineraries',{title,budget_amount:null,command_id:crypto.randomUUID()});setTitle('');setNotice('برنامه سفر قابل‌ویرایش ساخته شد.');await load()}catch(error){setNotice(failure(error))}}
  async function add(row:Itinerary){try{await api.post(`/itineraries/${row.id}/items`,{service_type:'attraction',title:'آیتم برنامه‌ریزی‌شده',day_number:1,position:row.items.length+1,command_id:crypto.randomUUID()});setNotice('آیتم افزوده شد؛ داده رزروشدنی بدون inventory معتبر قیمت‌گذاری نمی‌شود.');await load()}catch(error){setNotice(failure(error))}}
  if(!session)return <Gate message="برای ساخت برنامه سفر وارد شوید."/>;if(rows===null)return <Gate message="در حال بازیابی برنامه‌های سفر…"/>;
  return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">Editable Itinerary</span><h1>برنامه‌ریز سفر</h1><p>قیمت و موجودی فقط از Offer معتبر می‌آید؛ سایر آیتم‌ها نیازمند بررسی زنده‌اند.</p></div></header>{notice&&<p role="status" className="mb-4 rounded-xl bg-cyan-50 p-4">{notice}</p>}<form onSubmit={create} className="panel mb-5 flex gap-3"><input aria-label="عنوان برنامه سفر" className="flex-1 rounded-xl border p-3" value={title} onChange={e=>setTitle(e.target.value)} minLength={2} required/><button className="button primary">ساخت برنامه</button></form>{rows.length===0?<Gate message="برنامه ذخیره‌شده‌ای وجود ندارد."/>:rows.map(row=><section className="panel mb-5" key={row.id}><div className="flex items-center justify-between"><div><h2 className="font-black">{row.title}</h2><small>{row.status}</small></div><button className="button secondary" onClick={()=>add(row)}>افزودن آیتم</button></div>{row.items.map(item=><p className="mt-3 rounded-xl bg-slate-50 p-3" key={item.id}><b>روز {item.day_number.toLocaleString('fa-IR')}: {item.title}</b><small className="block text-amber-700">{item.availability_state==='needs_live_availability_check'?'نیازمند بررسی زنده موجودی':item.availability_state}</small></p>)}</section>)}</div>
}

export function DestinationListView(){
  const {api,session}=useAuth();const [rows,setRows]=useState<Destination[]|null>(null);const [error,setError]=useState('');useEffect(()=>{if(session)api.get<Destination[]>('/destinations').then(setRows).catch(e=>{setError(failure(e));setRows([])})},[api,session]);
  if(!session)return <Gate message="برای مشاهده کاتالوگ tenant وارد شوید."/>;if(rows===null)return <Gate message="در حال دریافت مقصدها…"/>;if(error)return <Gate message={error}/>;if(rows.length===0)return <Gate message="مقصد منتشرشده‌ای در کاتالوگ این tenant وجود ندارد."/>;
  return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">Destination Catalog</span><h1>مقصدهای سفر</h1></div></header><section className="grid gap-4 sm:grid-cols-2">{rows.map(row=><Link className="panel" href={`/destinations/${row.slug}`} key={row.id}><span className="tag">{row.kind}</span><h2 className="mt-3 text-xl font-black">{row.name_fa}</h2><p>{row.description}</p></Link>)}</section></div>
}

export function DestinationDetailView({slug}:{slug:string}){
  const {api,session}=useAuth();const [row,setRow]=useState<Destination|null|undefined>();const [error,setError]=useState('');useEffect(()=>{if(session)api.get<Destination>(`/destinations/${encodeURIComponent(slug)}`).then(setRow).catch(e=>{setError(failure(e));setRow(null)})},[api,session,slug]);
  if(!session)return <Gate message="برای مشاهده مقصد وارد شوید."/>;if(row===undefined)return <Gate message="در حال دریافت مقصد…"/>;if(row===null)return <Gate message={error||'مقصد پیدا نشد.'}/>;
  return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">{row.kind}</span><h1>{row.name_fa}</h1><p>{row.description}</p></div></header><section className="panel"><h2 className="font-black">خدمات متصل به Search Engine</h2>{Object.keys(row.service_counts).length===0?<p className="mt-3 text-slate-500">Offer تازه‌ای برای این مقصد موجود نیست؛ نتیجه جعلی نمایش داده نمی‌شود.</p>:Object.entries(row.service_counts).map(([type,count])=><p className="mt-2" key={type}>{type}: {count.toLocaleString('fa-IR')}</p>)}</section><section className="panel mt-5"><h2 className="font-black">نقشه و موقعیت</h2>{row.geo.latitude==null?<p>مختصات معتبر موجود نیست؛ fallback فهرستی فعال است.</p>:<p>{row.geo.latitude.toLocaleString('fa-IR')}، {row.geo.longitude?.toLocaleString('fa-IR')} — اتصال نقشه تا credential معتبر فعال نمی‌شود.</p>}</section></div>
}

export function MapListView(){
  const {api,session}=useAuth();const [rows,setRows]=useState<Destination[]|null>(null);const [selected,setSelected]=useState('');useEffect(()=>{if(!session)return;let active=true;api.get<Destination[]>('/destinations').then(data=>{if(active)setRows(data)}).catch(()=>{if(active)setRows([])});return()=>{active=false}},[api,session]);
  if(!session)return <Gate message="برای جست‌وجوی محدوده وارد شوید."/>;if(rows===null)return <Gate message="در حال دریافت داده مکانی معتبر…"/>;
  return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">Map / List</span><h1>جست‌وجوی خدمات روی محدوده</h1><p>در نبود credential نقشه، فقط فهرست و مختصات معتبر نمایش داده می‌شود؛ نقشه جعلی نداریم.</p></div></header><section className="grid gap-5 md:grid-cols-2"><div className="panel"><h2 className="font-black">فهرست مقصدها</h2>{rows.length===0?<p className="mt-3 text-slate-500">داده مکانی منتشرشده‌ای وجود ندارد.</p>:rows.map(row=><button className={`mt-3 block w-full rounded-xl border p-4 text-right ${selected===row.id?'border-cyan-700 bg-cyan-50':'border-slate-200'}`} key={row.id} onClick={()=>setSelected(row.id)}><b>{row.name_fa}</b><small className="block">{row.geo.latitude==null?'بدون مختصات':`${row.geo.latitude}، ${row.geo.longitude}`}</small></button>)}</div><div className="panel"><h2 className="font-black">محدوده نقشه</h2><p className="mt-3">قرارداد bounds و همگام‌سازی انتخاب آماده است. فعال‌سازی نقشه واقعی به credential معتبر Map Provider نیاز دارد.</p><button disabled className="button secondary mt-4">جست‌وجو در این محدوده</button></div></section></div>
}
