'use client';

import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import {useAuth} from '../../lib/api/auth-context';
import {ApiError, newId} from '../../lib/api/karenseir-client';

const money=(value:number)=>`${value.toLocaleString('fa-IR')} ریال`;
const fail=(e:unknown)=>e instanceof ApiError?e.message:'ارتباط با سرویس انجام نشد.';
function State({children}:{children:string}){return <p role="status" className="panel text-center text-slate-600">{children}</p>}
function Facts({value}:{value:Record<string,unknown>}){return <dl className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(value).map(([key,item])=><div className="rounded-xl bg-slate-50 p-3" key={key}><dt className="text-xs font-bold text-slate-500">{key.replaceAll('_',' ')}</dt><dd className="mt-1 text-sm">{Array.isArray(item)?item.map(part=>typeof part==='object'?JSON.stringify(part):String(part)).join(' · '):typeof item==='object'?JSON.stringify(item):String(item)}</dd></div>)}</dl>}
type Rental={id:string;title:string;city:string;property_type:string;capacity:number;bedrooms:number;details:Record<string,unknown>;units?:Array<{id:string;title:string;capacity:number;available_units:number;nightly_price:number}>};
type Tour={id:string;title:string;origin:string;destination:string;tour_type:string;details:Record<string,unknown>;departures?:Array<{id:string;starts_at:string;ends_at:string;remaining:number;base_price:number}>};
type Cruise={id:string;title:string;cruise_line:string;ship:string;departure_port:string;arrival_port:string;starts_at:string;nights:number;status:string;details:Record<string,unknown>};
type Visa={id:string;title:string;destination_country:string;visa_type:string;source_url:string;source_verified_at:string;details:Record<string,unknown>;guarantee:false;eligibility:string};

export function VacationRentalList(){const{api,session}=useAuth();const[rows,setRows]=useState<Rental[]|null>(null);const[city,setCity]=useState('');const[error,setError]=useState('');async function load(){setRows(null);try{setRows(await api.get(`/vacation-rentals${city?`?city=${encodeURIComponent(city)}`:''}`))}catch(e){setError(fail(e));setRows([])}}useEffect(()=>{if(!session)return;let active=true;api.get<Rental[]>('/vacation-rentals').then(data=>{if(active)setRows(data)}).catch(e=>{if(active){setError(fail(e));setRows([])}});return()=>{active=false}},[api,session]);if(!session)return <State>برای مشاهده موجودی سازمان خود وارد شوید.</State>;return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">Vacation Rental</span><h1>ویلا و اقامتگاه</h1><p>موجودی بازه‌ای، هزینه‌ها و قوانین از سامانه معتبر خوانده می‌شوند.</p></div></header><form className="panel mb-5 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();load()}}><input aria-label="شهر اقامتگاه" className="min-w-56 flex-1 rounded-xl border p-3" value={city} onChange={e=>setCity(e.target.value)} placeholder="مقصد"/><button className="button primary">جست‌وجوی اقامتگاه</button></form>{rows===null?<State>در حال دریافت اقامتگاه‌ها…</State>:error?<State>{error}</State>:rows.length===0?<State>اقامتگاه دارای موجودی معتبر یافت نشد؛ نتیجه ساختگی نمایش داده نمی‌شود.</State>:<section className="grid gap-4 md:grid-cols-2">{rows.map(r=><Link className="panel" key={r.id} href={`/villas/${r.id}`}><span className="tag">{r.property_type}</span><h2 className="mt-3 text-xl font-black">{r.title}</h2><p>{r.city} · ظرفیت {r.capacity.toLocaleString('fa-IR')} نفر · {r.bedrooms.toLocaleString('fa-IR')} اتاق</p></Link>)}</section>}</div>}

export function VacationRentalDetail({id}:{id:string}){const{api,session}=useAuth();const[row,setRow]=useState<Rental|null|undefined>();const[notice,setNotice]=useState('');const[checkIn,setCheckIn]=useState('');const[checkOut,setCheckOut]=useState('');useEffect(()=>{if(session)api.get<Rental>(`/vacation-rentals/${id}`).then(setRow).catch(e=>{setNotice(fail(e));setRow(null)})},[api,id,session]);async function reserve(unitId:string){try{const result=await api.post<{total_amount:number}>(`/vacation-units/${unitId}/reservations`,{check_in:`${checkIn}T12:00:00Z`,check_out:`${checkOut}T12:00:00Z`,guests:2,command_id:newId()});setNotice(`اقامت با مبلغ ${money(result.total_amount)} نگه‌داری شد؛ پرداخت هنوز لازم است.`)}catch(e){setNotice(fail(e))}}if(!session)return <State>برای رزرو وارد شوید.</State>;if(row===undefined)return <State>در حال بررسی موجودی…</State>;if(!row)return <State>{notice||'اقامتگاه یافت نشد.'}</State>;return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">{row.property_type}</span><h1>{row.title}</h1><p>{row.city} · ظرفیت {row.capacity.toLocaleString('fa-IR')} نفر</p></div></header>{notice&&<p role="status" className="mb-4 rounded-xl bg-cyan-50 p-4">{notice}</p>}<section className="panel mb-5 grid gap-3 sm:grid-cols-2"><label>ورود<input aria-label="تاریخ ورود" type="date" className="mt-2 block w-full rounded-xl border p-3" value={checkIn} onChange={e=>setCheckIn(e.target.value)}/></label><label>خروج<input aria-label="تاریخ خروج" type="date" className="mt-2 block w-full rounded-xl border p-3" value={checkOut} onChange={e=>setCheckOut(e.target.value)}/></label></section>{row.units?.map(u=><article className="panel mb-4" key={u.id}><h2 className="font-black">{u.title}</h2><p>ظرفیت {u.capacity.toLocaleString('fa-IR')} · {money(u.nightly_price)} هر شب</p><button disabled={!checkIn||!checkOut} className="button primary mt-3" onClick={()=>reserve(u.id)}>بررسی و نگه‌داری موجودی</button></article>)}</div>}

export function TourList(){const{api,session}=useAuth();const[rows,setRows]=useState<Tour[]|null>(null);const[destination,setDestination]=useState('');async function load(){setRows(null);try{setRows(await api.get(`/tour-products${destination?`?destination=${encodeURIComponent(destination)}`:''}`))}catch{setRows([])}}useEffect(()=>{if(!session)return;let active=true;api.get<Tour[]>('/tour-products').then(data=>{if(active)setRows(data)}).catch(()=>{if(active)setRows([])});return()=>{active=false}},[api,session]);if(!session)return <State>برای مشاهده تورهای سازمان خود وارد شوید.</State>;return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">Tour Booking</span><h1>تورهای قابل رزرو</h1><p>هر حرکت ظرفیت، مهلت و قیمت مستقل دارد.</p></div></header><form className="panel mb-5 flex gap-3" onSubmit={(e:FormEvent)=>{e.preventDefault();load()}}><input aria-label="مقصد تور" className="flex-1 rounded-xl border p-3" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="مقصد"/><button className="button primary">جست‌وجوی تور</button></form>{rows===null?<State>در حال دریافت تورها…</State>:rows.length===0?<State>تور با ظرفیت معتبر یافت نشد؛ Offer جعلی نمایش داده نمی‌شود.</State>:rows.map(r=><Link className="panel mb-4 block" href={`/tours/${r.id}`} key={r.id}><span className="tag">{r.tour_type}</span><h2 className="mt-3 text-xl font-black">{r.title}</h2><p>{r.origin} ← {r.destination}</p></Link>)}</div>}

export function TourDetail({id}:{id:string}){const{api,session}=useAuth();const[row,setRow]=useState<Tour|null|undefined>();const[notice,setNotice]=useState('');useEffect(()=>{if(session)api.get<Tour>(`/tour-products/${id}`).then(setRow).catch(e=>{setNotice(fail(e));setRow(null)})},[api,id,session]);async function reserve(departureId:string){try{const result=await api.post<{total_amount:number;voucher:null}>(`/tour-departures/${departureId}/reservations`,{travellers:2,room_type:'double',command_id:newId()});setNotice(`ظرفیت با مبلغ ${money(result.total_amount)} نگه‌داری شد. واچر فقط پس از پرداخت و تأیید صادر می‌شود.`)}catch(e){setNotice(fail(e))}}if(!session)return <State>برای رزرو تور وارد شوید.</State>;if(row===undefined)return <State>در حال دریافت برنامه تور…</State>;if(!row)return <State>{notice||'تور یافت نشد.'}</State>;return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">{row.tour_type}</span><h1>{row.title}</h1><p>{row.origin} ← {row.destination}</p></div></header>{notice&&<p role="status" className="mb-4 rounded-xl bg-cyan-50 p-4">{notice}</p>}<section className="panel mb-5"><h2 className="font-black">خدمات و برنامه روزبه‌روز</h2><Facts value={row.details}/></section>{row.departures?.map(d=><article className="panel mb-4" key={d.id}><h2 className="font-black">حرکت {new Date(d.starts_at).toLocaleDateString('fa-IR')}</h2><p>{d.remaining.toLocaleString('fa-IR')} صندلی باقی‌مانده · از {money(d.base_price)}</p><button className="button primary mt-3" onClick={()=>reserve(d.id)}>بررسی ظرفیت و قیمت</button></article>)}</div>}

export function CruiseList(){const{api,session}=useAuth();const[data,setData]=useState<{items:Cruise[];provider_status:string}|null>(null);useEffect(()=>{if(session)api.get<{items:Cruise[];provider_status:string}>('/cruises').then(setData).catch(()=>setData({items:[],provider_status:'BLOCKED_EXTERNAL_CREDENTIAL'}))},[api,session]);if(!session)return <State>برای مشاهده کاتالوگ وارد شوید.</State>;return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">Cruise Foundation</span><h1>سفر دریایی و کروز</h1><p>مسیر، کشتی، کابین و هزینه‌ها بدون Provider زنده به‌عنوان موجودی قطعی نمایش داده نمی‌شوند.</p></div></header>{!data?<State>در حال دریافت کاتالوگ…</State>:<><p role="status" className="mb-5 rounded-xl bg-amber-50 p-4">رزرو زنده کروز: مسدود تا اتصال Provider قراردادی</p>{data.items.length===0?<State>سفر دریایی دارای منبع معتبر موجود نیست.</State>:data.items.map(r=><article className="panel mb-4" key={r.id}><span className="tag">{r.status}</span><h2 className="mt-3 font-black">{r.title}</h2><p>{r.cruise_line} · {r.ship}</p><p>{r.departure_port} ← {r.arrival_port} · {r.nights.toLocaleString('fa-IR')} شب</p><button disabled className="button secondary mt-3">Live Provider Unavailable</button></article>)}</>}</div>}

export function VisaList(){const{api,session}=useAuth();const[rows,setRows]=useState<Visa[]|null>(null);useEffect(()=>{if(session)api.get<Visa[]>('/visa-products').then(setRows).catch(()=>setRows([]))},[api,session]);if(!session)return <State>برای بررسی خدمت ویزا وارد شوید.</State>;return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">Visa Services</span><h1>بررسی و درخواست ویزا</h1><p>نتیجه اولیه مشورتی است؛ تصمیم نهایی فقط با سفارت یا مرجع رسمی است.</p></div></header>{rows===null?<State>در حال دریافت اطلاعات timestamp‌دار…</State>:rows.length===0?<State>خدمت ویزای دارای منبع رسمی در این سازمان منتشر نشده است.</State>:rows.map(r=><Link className="panel mb-4 block" href={`/visa/${r.id}`} key={r.id}><span className="tag">{r.visa_type}</span><h2 className="mt-3 font-black">{r.title}</h2><p>{r.destination_country} · نیازمند بررسی انسانی</p></Link>)}</div>}

export function VisaDetail({id}:{id:string}){const{api,session}=useAuth();const[rows,setRows]=useState<Visa[]|null>(null);const[notice,setNotice]=useState('');useEffect(()=>{if(session)api.get<Visa[]>('/visa-products').then(setRows).catch(()=>setRows([]))},[api,session]);const row=rows?.find(x=>x.id===id);async function start(){try{const result=await api.post<{id:string}>(`/visa-products/${id}/applications`,{purpose:'tourism',travel_at:new Date(Date.now()+45*86400000).toISOString(),command_id:newId()});setNotice(`پرونده ${result.id} ایجاد شد؛ صدور تضمین نمی‌شود.`)}catch(e){setNotice(fail(e))}}if(!session)return <State>برای شروع پرونده وارد شوید.</State>;if(rows===null)return <State>در حال بررسی منبع رسمی…</State>;if(!row)return <State>خدمت ویزا یافت نشد.</State>;return <div className="dashboard container"><header className="dashboard-title"><div><span className="eyebrow">{row.visa_type}</span><h1>{row.title}</h1><p>{row.destination_country} · منبع آخرین بار {new Date(row.source_verified_at).toLocaleDateString('fa-IR')} بررسی شده است.</p></div></header>{notice&&<p role="status" className="mb-4 rounded-xl bg-cyan-50 p-4">{notice}</p>}<section className="panel"><h2 className="font-black">شرایط و مدارک</h2><Facts value={row.details}/><a className="mt-3 block text-cyan-800 underline" href={row.source_url} rel="noreferrer" target="_blank">مشاهده منبع رسمی</a><p className="mt-4 rounded-xl bg-amber-50 p-3">کارن‌سیر صدور، شرایط احراز یا زمان پردازش را تضمین نمی‌کند.</p><button className="button primary mt-4" onClick={start}>شروع درخواست و بررسی انسانی</button></section></div>}
